### ISSUE TITLE
Github release as draft

### ISSUE THREAD

**Issue by MichaelMure** [webpro/release-it#100]
It would be neat to have an option to make a Github release as a draft instead of a published release.

That would allow to edit the release before the actual publish. It also help when you setup release-it the first time and don't want to screw things up.

**Comment by MichaelMure** [comment]
It's just a flag to set in the request: https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by webpro** [comment]
There is a `github.preRelease` config for this, set it to `true` to make a draft.

**Comment by MichaelMure** [comment]
That's not the same thing.
* `preRelease` is a release considered unstable, preview, alpha ...
* `draft` is a release that is not public yet on github, awaiting for further changes before publishing

**Comment by webpro** [comment]
I'm sorry, you're right. I will add it soon, easy enough.

**Comment by MichaelMure** [comment]
Yeaah o/
