### ISSUE TITLE
Use GitHub SSH key instead of token

### ISSUE THREAD

**Issue by MikeSharov** [webpro/release-it#103]
Is there a way to use the SSH key instead of having to create an access token and save it as an environment variable?

**Comment by webpro** [comment]
Under the hood, release-it uses Git, and should "just work" with your GitHub SSH key.

Can you e.g. `git push` from your repo?

Also see #91.

**Comment by MikeSharov** [comment]
I can do push and other commands so the SSH is set up properly. Using your awesome tool works when I have a GITHUB_TOKEN environment variable, but as soon as I remove it I get errors complaining that it's not there. Any ideas?

**Comment by webpro** [comment]
Can you please try and run it with `--debug --verbose` (`-eV`) arguments; does it log anything valuable?

**Comment by MikeSharov** [comment]
Does this help? This is the only error message: 

ERROR About to release to GitHub, but GITHUB_TOKEN environment variable not set
Error: Error: About to release to GitHub, but GITHUB_TOKEN environment variable not set
    at tasks.run.catch.error (C:\DEV\ui-core\node_modules\release-it\lib\release.js:40:15)
    at tryCatchReject (C:\DEV\ui-core\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (C:\DEV\ui-core\node_modules\when\lib\makePromise.js:804:4)
    at Rejected.when (C:\DEV\ui-core\node_modules\when\lib\makePromise.js:625:4)
    at Pending.run (C:\DEV\ui-core\node_modules\when\lib\makePromise.js:483:13)
    at Scheduler._drain (C:\DEV\ui-core\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\DEV\ui-core\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error Command failed with exit code 1.

**Comment by webpro** [comment]
Thanks, now I fully understand. Indeed release-it assumes a `GITHUB_TOKEN`. And uses [node-github](https://github.com/mikedeboer/node-github) to make a GitHub release. However, it looks like it doesn't include a way to provide the SSH key for [authentication](https://github.com/mikedeboer/node-github#authentication). So, I'm going to close this ticket, but I'm happy to discuss further if there are any options to make this happen.

**Comment by miqmago** [comment]
This is little weird now...
In my `.git/config` file I've setup an origin and a github remotes that both use ssh:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@mygitserver.com:user/repo.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[remote "github"]
	url = git@github.com:user/repo.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = github
	merge = refs/heads/master
```

Also in `.release-it.json`:
```json
{
    "hooks": {
        "before:init": ["npm run build", "git branch master -u github/master"],
        "after:github:release": "git push -u origin"
    },
    "git": {
        "tagName": "v${version}",
        "addUntrackedFiles": true,
        "requireCleanWorkingDir": false,
        "pushArgs": "-u github"
    },
    "github": {
        "release": true
    },
    "npm": {
        "publish": true,
        "access": "public"
    }
}
```

If I use `release-it` directly it fails with:
```
$ release-it 
✔ npm run build
ERROR Environment variable "GITHUB_TOKEN" is required for GitHub releases.
Documentation: https://git.io/release-it-github
```

Then I've created a .env file with empty token:
```
GITHUB_TOKEN=""
```

Then I run release, it complains about variable is needed, but it successfully releases to npm and to github...

```
$ npm run release

> repo@1.1.1 release
> dotenv release-it --

✔ npm run build
✔ git branch master -u github/master
WARNING Environment variable "GITHUB_TOKEN" is required for automated GitHub Releases.
WARNING Falling back to web-based GitHub Release.
```

Also noted that if the `[branch]` is not configured to `github` then it fails, as seems is trying to login to `mygitserver.com`. This is the reason of `git branch master -u github/master`

**Comment by kaijurgeit** [comment]
Hi,

follow the instructions here: [](https://github.com/release-it/release-it/blob/main/docs/github-releases.md)

1. In package.json or .release-it.json add `"github": { "release": true }`
2. [Generate token on GitHub](https://github.com/settings/tokens/new?scopes=repo&description=release-it)
3. Add token to system vars e.g. in windows: Control Panel -> Environment Variables (name: GITHUB_TOKEN)
4. Add env: GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} to your .github/workflows/release.yml (Not sure if this is really required)
5. Restart your terminal (e.g. VS Code)
6. `npm run release`
