### ISSUE TITLE
Deactivate verbose in non-interactive mode

### ISSUE THREAD

**Issue by marcuspoehls** [webpro/release-it#106]
I run release-it in non-interactive mode and don’t want it to output logs execept errors. Is there a chance to deactive the `verbose` option when running `non-interactive`?

You can see within the [lib/config.js](https://github.com/webpro/release-it/blob/master/lib/config.js) in method `mergeOptions` that `verbose` is set to `true`:

```
mergedOptions.verbose = mergedOptions['non-interactive'] || mergedOptions.debug || mergedOptions.verbose;
```

Any chance to deactive verbose for non-interactive?

**Comment by webpro** [comment]
Good point, @marcuspoehls. Initially, I thought it makes sense to have more verbose output in non-interactive mode, especially for people new to this tool. But you can't opt-out now. It should be the other way around and enable to opt-in with `--verbose`.

In the meantime, I'm working on a complete rewrite, and I will take this into account. I hope you can live with this for a little while.

**Comment by marcuspoehls** [comment]
@webpro Hey Lars, your solution is exactly what I'm thinking of. Opt-in to `verbose` with `--verbose` if wanted.

Yeah, it's fine to have the extra output for a while.

I'm building a command line tool that makes use of release-it to bump the version, tag a release, push changes as part of a deployment process. The process itself contains multiple steps and currently release-it outputs text that shouldn't be there except an error occurs :)

Thank you for keeping this change into account. I really appreciate your work and effort that goes into release-it! :handshake:

**Comment by webpro** [comment]
Thanks! I'll leave this ticket open until it's available.

You could also fork this repo, change that line and use this in the meantime (you can `npm install` from that github repo).

**Comment by marcuspoehls** [comment]
You're right, a fork would solve this problem. Thanks for the hint, will do it 👍

**Comment by webpro** [comment]
I've just [released](https://github.com/webpro/release-it/releases) the first beta of v3, which includes this feature. Feel free to check it out and I'm happy to hear any feedback.
