### ISSUE TITLE
Even when the dist.repo is false, the git add command fails

### ISSUE THREAD

**Issue by sakshamsaxena** [webpro/release-it#107]
If I have this config in my `grunt-release-it` task :
```
'release-it': {
      options: {
        'non-interactive': true,
        'verbose': true,
        'pkgFiles': ['package.json'],
        'increment': '',
        'buildCommand': 'grunt yui && grunt build',
        'changelogCommand': 'git log --pretty=format:"* %s (%h)" [REV_RANGE]',
        'src': {
          'commitMessage': 'Release v%s',
          'tagName': '%s',
          'tagAnnotation': 'Release v%s',
          'pushRepo': 'origin easing-up-the-release-process'
        },
        'dist': {
        	'repo': false
        },
        'npm': {
          'publish': false,
          'publishPath': 'lib/'
        }
      }
    },
```

then on a dry run I get the following :
```
Running "release-it" task
[dry-run] git config --get remote.origin.url
git@github.com:sakshamsaxena/p5.js.git
Release source repo
[dry-run] git rev-parse --git-dir
.git
[dry-run] bump [ 'package.json' ] 0.5.13
[dry-run] grunt yui && grunt build
[dry-run] git add package.json
[dry-run] git add dist --all
[dry-run] git diff-index --name-only HEAD --exit-code
Gruntfile.js
package.json
tasks/release/release-p5.js
[dry-run] git commit --message="Release v0.5.13"
[dry-run] git tag --annotate --message="Release v0.5.13" 0.5.13
[dry-run] git push --follow-tags origin easing-up-the-release-process
[verbose] No "dist.repo" configuration provided, done.
```

Notice the `git add dist --all` above. On actual execution, it does fail saying no reference to dist. 

I did some basic investigation, and I feel that [this line](https://github.com/webpro/release-it/blob/8f5bd6126467cf65677baef457dc4b7dd0bdc895/lib/tasks.js#L183) is a bit out of place. 

Could you please look into it and suggest ? Thanks !

**Comment by sakshamsaxena** [comment]
Posted this here instead of the grunt task repo as the code essentially lies here :sweat_smile:

**Comment by webpro** [comment]
Hi, @sakshamsaxena. Here is an explanation:

You can have a `buildCommand` that results in files in the `dist.baseDir` directory. Those files can be included in for staging with the release (`git add dist --all`).

I agree it's a bit misleading to have `dist.baseDir`, I will think about how this might be improved .

So, either on your needs you can update `dist.baseDir` to. e.g. `"lib"` to include those files in the release commit, or set it to `false` to not stage extra build files.
