### ISSUE TITLE
Add option to specify --access on npm publish (public vs private packages)

### ISSUE THREAD

**Issue by joerideg** [webpro/release-it#108]
Hi!

Scoped npm packages default to `--access restricted`, probably to ensure you will not accidentally publish a private package to the public npm.  So when publishing a public scoped package on npm you **need** to specify `--access public`. 

This is currently impossible with release-it unfortunately as I have no control over cli commands passed to npm.

I do have a work around and that is to set the npm publish property to false, and then in afterReleaseCommand do `npm publish --access public --tag ${npm.tag}`. This workaround isnt nice because it takes away the option to **not** publish to npm if you do not want to.

It would be nice to be able to set the access property in the .release.json in the npm object.

cheers,
Joeri

**Comment by webpro** [comment]
Thanks for bringing this up. I will definitely take scoped packages into account in v3, which I'm currently working on. Will leave this ticket open for reference.

**Comment by joerideg** [comment]
Just discovered that the [npm docs](https://docs.npmjs.com/misc/scope#publishing-public-scoped-packages-to-the-primary-npm-registry) state that the --access flag is only necessary on *initial* publication. Just letting you know.

**Comment by webpro** [comment]
I've just [released](https://github.com/webpro/release-it/releases) the first beta of v3, which includes this feature. Feel free to check it out and I'm happy to hear any feedback.

**Comment by joerideg** [comment]
Using the new v3 the access option allows me to publish scoped packages!

**Comment by webpro** [comment]
Great!
