### ISSUE TITLE
prompt options not respected when using non-interactive

### ISSUE THREAD

**Issue by joerideg** [webpro/release-it#109]
The fix for #85 provided the solution for my problem there. I did test it and back then I believe it worked. I just came back around to this project and now it doesnt seem to work. The general problem being that any settings in the `prompt` object do not seem to be respected by release-it when using non-interactive mode.

Did a regression happen somehow? I would really like to be able to specify wheather I want to commit, tag or push or not when using non-interactive mode.

**Comment by webpro** [comment]
Hi @joerideg, the `prompt` config has never been used other than just for the default answers during interactive mode.

I'm currently working on a rewrite (v3) and what you describe will be included by supporting e.g. boolean `src.commit`,`src.tag`, etc. settings. Will leave this ticket open for reference (#72 is also relevant).

**Comment by joerideg** [comment]
Ah ok, so weird that I [apparently thought it was working](https://github.com/webpro/release-it/issues/85#issuecomment-287721751).

Cool so I'll just wait for v3 then! I really like the tool!

**Comment by webpro** [comment]
Reading this again, it was also a misunderstanding from my side:

> However we would like to have the option to not set a tag everytime we create a prerelease **without having to go throug the interactive process.**

Anyway, it'll be there soon :-)

**Comment by webpro** [comment]
I've just [released](https://github.com/webpro/release-it/releases) the first beta of v3, which includes this feature. Feel free to check it out and I'm happy to hear any feedback.

**Comment by joerideg** [comment]
Unfortunately installing globally and running release-it@3.0.0-beta.1 gives me the following error:
````
$ release-it -V
/home/jdegooijer/.npm-global/lib/node_modules/release-it/lib/tasks.js:15
async function run() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
````

**Comment by webpro** [comment]
I've probably been using it wrong, so I've just [released a new version](https://github.com/webpro/release-it/releases) without @std/esm.

**Comment by joerideg** [comment]
Getting another error when installing and using release-it@3.0.0-beta.2: 
```shell
/home/jdegooijer/.npm-global/lib/node_modules/release-it/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import { version, help } from './cli';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jdegooijer/.npm-global/lib/node_modules/release-it/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Comment by webpro** [comment]
Thanks for trying again, @joerideg! But ouch, this is getting embarrassing. Not sure what went wrong with `npm link` or something... Just released [3.0.0-beta.3](https://github.com/webpro/release-it/releases/tag/3.0.0-beta.3).

**Comment by joerideg** [comment]
It works it works! :) awesome thanks!

**Comment by webpro** [comment]
You're welcome, thanks for the feedback!
