### ISSUE TITLE
support for releases without package.json

### ISSUE THREAD

**Issue by ksatirli** [webpro/release-it#111]
Hey @webpro! 

Huge fan of _Release It!_ and been happily using it for a few years, though always with projects that had a `package.json` file.

I notice that you started working on supporting projects that do not have a `package.json` file in https://github.com/webpro/release-it/commit/766e5eb4cd601050a0064164fed66b34a4d07b44.

Is this something that will be available in `3.0.0`?

**Comment by webpro** [comment]
Hi, @ksatirli! Thanks you so much for the shout out, it's truly appreciated!

This tool has supported projects without a `package.json` since that very commit (ending up in v2), and will continu to do so in v3. You can also explicitly set this to an empty array: `pkgFiles: []`. Does this answer your quesion?

**Comment by ksatirli** [comment]
@webpro totally my pleasure! Thank _you_ for sharing.

No dependency on `package.json` is great news! So I guess I'm doing something wrong on my side. I'd love some feedback on this to hopefully figure out how to use `Release It!` for _all_ my projects 😃.

Here's my `.release.json`:

```
{
    "non-interactive": false,
    "verbose": true,
    "src": {
      "commitMessage": "Release %s",
      "tagName": "%s",
      "tagAnnotation": "Release %s"
    },
    "changelogCommand": "git log --pretty=format:'* %s (%h)' [REV_RANGE]",
    "requireCleanWorkingDir": true,
    "dist": {
        "repo": false,
        "pkgFiles": []
    },
    "npm": {
        "publish": false
    },
    "github": {
        "release": false
    }
}
```

I've added an empty `pkgFiles` entry like you did in [.release.json](https://github.com/webpro/release-it/blob/fe6a0b62e47d641d3803af15433705e2ff531d2a/.release.json#L6).

Next, I've created a manual Git tag:

```
git tag
  0.4.0
```

Finally, I run the following: `release-it --config .release.json --dry-run --major` (also tried `--increment "0.5.0"` and other options, all to no avail. Adding `--always` did not make a difference either.

Here's the message I get in `v3.0.0-beta.4`:

```
$ git describe --tags --abbrev=0
fatal: No tags can describe '64dd93f505b3e100a379b3979c27fa2aba1ce6f1'.
Try --always, or create some tags.
ERROR Invalid Version: undefined
```

Any thoughts / help would be very much appreciated!

**Comment by webpro** [comment]
I can't reproduce your issue. Can you describe the steps to reproduce it?

However, I did spot a bug in release-it v3 re. `requireCleanWorkingDir`. I've just fixed this in a [new beta](https://github.com/webpro/release-it/releases/tag/3.0.0-beta.5). Thanks! Also:

* The `--major` is not supposed to be used like that; it should be `release-it major` (no dashes).
* There is no `--always` option.

**Comment by ksatirli** [comment]
I'll try!

I have a code base without a `package.json` and Beta 5 of _Release It!_. The `.release.json` is the one I have posted above.

When I am in the directory of the repository I want to release, I run the following: `release-it --dry-run minor` at which point I get the following lines as an error message:

```
$ git describe --tags --abbrev=0
fatal: No tags can describe '64dd93f505b3e100a379b3979c27fa2aba1ce6f1'.
Try --always, or create some tags.
ERROR Invalid Version: undefined
```

Note the `--always` reference in there; it threw me off; I thought that was an option of _Release It_, but its just `git`.

The `64dd93f505b3e100a379b3979c27fa2aba1ce6f1` refers to a commit-ish.

Thoughts?

**Comment by webpro** [comment]
Ah, it's indeed not clear where the error is coming from, apologies for that.

Maybe you ran into this issue: https://stackoverflow.com/a/41605474?

**Comment by ksatirli** [comment]
Ah that's indeed it. Great catch Lars! 

Thank you :)
