### ISSUE TITLE
How do I actually use the access token?

### ISSUE THREAD

**Issue by sw-yx** [webpro/release-it#118]
So I have a github access token.. and I have no idea what to do with it! the docs say:

```
Make this available as the environment variable defined with github.tokenRef. Example:

export GITHUB_TOKEN="f941e0..."
```

but what does this actually mean? where do I put it? obviously not in package.json because that would get uploaded?

**Comment by webpro** [comment]
Hi @sw-yx! Are you on *nix/macOS? Then you can execute that on the command line in your terminal. The quotes are not required in this case. For instance:

```
$ export GITHUB_TOKEN=f941e0...
$ release-it
```

Alternatively, you can put it on one line to make the environment variable only available to the release-it process:

```
$ GITHUB_TOKEN=f941e0... release-it
```

On Windows I believe it's something like this:

```
$ set GITHUB_TOKEN=f941e0...
```

Does this help?

**Comment by sw-yx** [comment]
yes! it helped! (i am on macOS). i guess i have never seen the `export` command before so that really threw me off, i was thinking i had to add it to some secret `release-it` config somewhere.

thank you SO. MUCH. for this thing. it is absolutely amazing and you are a rockstar.

**Comment by webpro** [comment]
Glad you figured it out. Thanks so much for the super kind words! 😊
