### ISSUE TITLE
404 error on release

### ISSUE THREAD

**Issue by simonwjackson** [webpro/release-it#120]
```
? Create a release on GitHub (Release 0.0.1)? Yes
$ node-github releases#createRelease
ERROR 404 Not Found: Not Found ()
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by webpro** [comment]
Hi @simonwjackson!

First of all, the error isn't very descriptive, so that should be improved.

Looks like the tag in your repo can't be found on GitHub origin. The tag must be present before a GitHub release can be attached to it. Did you push the commit + tag before this question?

**Comment by simonwjackson** [comment]
It turns out that my GitHub token didn't have the correct permissions to preform the tag operation. Seems to be working now

**Comment by webpro** [comment]
Good to hear it's working for you.

I guess the pushing operation (which includes the tag) should have failed in the first place, right? If you think there's anything that could be improved on release-it side, let me know.
