### ISSUE TITLE
Attempts to publish to NPM when npm.publish=false in config.

### ISSUE THREAD

**Issue by LorneCurrie** [webpro/release-it#122]
Just looking into this tool and I have one question.  When I run the tool interactively, `Publish to NPM` default is set to "N".  When I attempt to run the tool with '-n' and with the setting `npm.publish=false` the tool attempts to publish to npm.  Am I missing a config?

```
{
  "verbose": true,
  "non-interactive": false,
  "prereleaseId": "rc",
  "src": {
    "commitMessage": "Release %s",
    "tagName": "%s",
    "tagAnnotation": "Release %s"
  },
  "npm": {
    "publish": true
  },
  "prompt": {
    "src": {
      "status": "Y",
      "commit": "Y",
      "tag": "Y",
      "push": "Y",
      "release": "Y",
      "publish": "N"
    }
  }
}
```

**Comment by LorneCurrie** [comment]
Sorry, found my issue.

**Comment by webpro** [comment]
Hi, @LorneCurrie. Sorry to to hear you might have had an unwanted npm publish. But glad you've fixed it, and that you're giving release-it a shot!
