### ISSUE TITLE
[Bug] Confirm prompt is blocking execution in non-interactive mode

### ISSUE THREAD

**Issue by sgal** [webpro/release-it#123]
Since version `3.1.0` the non-interactive mode is blocked by `confirm` prompt.
I mean this https://github.com/webpro/release-it/blob/master/lib/tasks.js#L60. 
As far as I see it was introduced with this commit https://github.com/webpro/release-it/commit/3618e5ab2d23151cb6a74777be5d52900511ffdd.

Documentation does not state any way around it.

**Expected behaviour**
Prompt is triggered only in interactive mode.

**Environment**
Node: 6.11.1
Npm: 4.6.1
release-it: 3.1.0

**Comment by webpro** [comment]
Thanks for the report, @sgal!

Just made a fix, and confirmed it works by releasing release-it itself with `release-it -n` in [v3.1.1](https://github.com/webpro/release-it/releases/tag/3.1.1).
