### ISSUE TITLE
Support for repos with periods in name | parse-repo issue

### ISSUE THREAD

**Issue by simshanith** [webpro/release-it#125]
See dgoguerra/parse-repo#1 for an explanation and dgoguerra/parse-repo#2 for a PR.

See my fork [simshanith/release-it](/simshanith/release-it) for a temporary workaround - example working usage at [simshanith/pi.simloovoo.com](/simshanith/pi.simloovoo.com)

**Comment by simshanith** [comment]
Apologies for my generally vague starting issue.

The underlying `parse-repo` module does not currently support my [Github repository](/simshanith/pi.simloovoo.com), `git@github.com:simshanith/pi.simloovoo.com.git`, failing to parse it correctly due to the `.` (periods) in the repository name.

The result is the `release-it` command aborting during the `github.release` step, failing to identify the owner of the repository, similar to semantic-release/semantic-release#48. The previous steps succeeded successfully, but the remainder did not.

I implemented a fix and made a PR  dgoguerra/parse-repo#2

Too stubborn to change my repo name 😅

**Comment by webpro** [comment]
Thanks, @simshanith! Totally agree that periods in the repo name should be supported.

I see that [dgoguerra/parse-repo](https://github.com/dgoguerra/parse-repo) seems kind of abandoned/unmaintained. I think I was OK with it before, since there were no alternatives, and it has tests.

So let's see if your PS gets merged and released. Otherwise, we can either look for similar packages, or maybe you can publish your fork.

**Comment by webpro** [comment]
I just got a PR from Greenkeeper updating parse-repo. So that's merged and release-it was [updated](https://github.com/webpro/release-it/releases/tag/3.1.2) as well. Thanks again.

**Comment by simshanith** [comment]
@webpro please see my note on commit 826a033 - the issue may persist

**Comment by simshanith** [comment]
As a follow-up, upon further review `1.0.2` _should_ include the necessary fix. However, something like [repo-utils/parse-github-repo-url](/repo-utils/parse-github-repo-url) may be more stable with more eyes on it. Glad I got the current dependency to work at least!

**Comment by webpro** [comment]
Thanks for the heads up, @simshanith. I think parse-repo v1.0.2 includes the fix indeed.
