### ISSUE TITLE
ssh:// url pattern

### ISSUE THREAD

**Issue by jfairley** [webpro/release-it#139]
I tried to create a github release with a Jenkins machine. My build failed on the step to use `node-github` to create the release.

Long story short, my configured URL format (`ssh://git@github.com/org/repo.git`) wasn't supported, so the "owner" wasn't properly parsed out. I had to step through the `release-it` source code to figure out what went wrong...

Anyway, I updated my Jenkins config to use a URL pattern that is supported, so I'm good now, but I also submitted an issue to `parse-repo` for an updated URL pattern: https://github.com/dgoguerra/parse-repo/issues/3

I just wanted to give @webpro a heads up that an updated dependency may be coming down the pike. 

Cheers! 🍻

**Comment by webpro** [comment]
Thanks! I'm also open to switch to another git url parser (had an issue before in #125). Let's see if/how this gets resolved first.

**Comment by jfairley** [comment]
@webpro FYI, the fix has gone into `parse-repo@1.0.4`.

**Comment by webpro** [comment]
Thanks, @jfairley! Greenkeeper notified me already, and it's in the latest release here.
