### ISSUE TITLE
Does not update package-lock.json

### ISSUE THREAD

**Issue by ShMcK** [webpro/release-it#147]
Might consider updating the versions for package-lock.json or yarn.lock if they exist.

This could be accomplished with a quick check:
- if "package-lock.json" exists, run `npm i`
- if "yarn.lock" exists, run `yarn`

This way versions of locked dependencies won't be out of sync with published versions.

**Comment by webpro** [comment]
This isn't automated indeed. For now you can also add the file to the `pkgFiles` config array (the default is `["package.json"]`). Does that work for you?

**Comment by ShMcK** [comment]
That works. I hadn't realized there was a configuration option.

**Comment by webpro** [comment]
Good to hear, @ShMcK.

**Comment by dinomiike** [comment]
Can you share your .release-it.json and command? I am using the following but it doesn't seem to be using my config file or adding package-lock.json to the commit.

```
{
  "non-interactive": true,
  "pkgFiles": ["package.json", "package-lock.json"],
  "verbose": true,
  "dist": {
    "repo": "git@github.com:<myCompany>/<myRepoName>.git",
    "pkgFiles": ["package.json", "package-lock.json"]
  }
}
```
`"release": "release-it -n --no-requireUpstream --no-requireCleanWorkingDir --src.tagName='v%s'"`

I tried adding -c and my config file path but it doesn't work. This is running on CI so it's a little hard to debug. I also tried it with just pkgFiles, with just dist/pkgFiles, still doesn't seem like it's using the file config file, or maybe I'm doing something else wrong..

**Comment by webpro** [comment]
@dinomiike,

- Is the config file named `.release-it.json`?
- Is `.release-it.json` in the root of the project next to `package.json`?
- Is `release-it` executed from the root of the project?

**Comment by dinomiike** [comment]
@webpro thanks for the reply! I had some weird caching issue in my CI that wasn't seeing my updated command. I was able to find a fix for it in my CI settings. Using `pkgFiles` does exactly what we need. Thank you for creating and maintaining this tool!
