### ISSUE TITLE
Don't ask to publish to npm if private === true

### ISSUE THREAD

**Issue by jrschumacher** [webpro/release-it#16]
Would it be possible to prevent the `Publish "..." to npm?` if the package.json contains `"private": true`?

**Comment by webpro** [comment]
The default for `publish` is `false`. So you mean it should not publish to npm even for `"publish": true` in a private package? I guess in that case npm will refuse to publish anyway?

**Comment by jrschumacher** [comment]
Yea I'm just thinking of some of our jr devs who might be confused. Given what you said I'd feel far less concerned of accidentally leaking private code but not showing up entirely would be nice assuming it wouldn't conflict with others existing workflow.

**Comment by webpro** [comment]
It's still a nice feature indeed. I'll see what I can do in the next few days. Or, PR welcome!

**Comment by jrschumacher** [comment]
I'll take a look and see if it's something I can do ;)

**Comment by webpro** [comment]
Done in 7bdadb6351efb121c4cec109072577bb62a9ade3. Released as v0.0.14. Please let me know if it works for you.

**Comment by jrschumacher** [comment]
@webpro awesome I'll check it out

**Comment by jrschumacher** [comment]
@webpro works great thanks!

**Comment by webpro** [comment]
Thanks for the feedback, @jrschumacher!
