### ISSUE TITLE
Parameter about github API endpoint

### ISSUE THREAD

**Issue by vchagaev** [webpro/release-it#161]
Please add a parameter about github API to config file. We use github enterprise and release-it does not work because it uses api endpoint from repo-params but it is incorrect.

**Comment by webpro** [comment]
Hi @vchagaev. I'm not sure what you mean. What exactly is incorrect?

Are you referring to the `host` for the GitHub API client? It is set to an empty string for repos in the `github.com` domain (non-enterprise), and `pathPrefix` is set to `""`.

For GH enterprise, this is the `host` of the repo, and `'/api/v3'`, respectively.

Source: https://github.com/webpro/release-it/blob/master/lib/github-client.js#L21-L22

**Comment by vchagaev** [comment]
Hi @webpro, yes I'm referring to the `host`. In my case API endpoint for github (`host`) is not the same as repo. 
Also I think it is reasonable to add `pathPrefix` to config.

**Comment by webpro** [comment]
OK, no problem. Hadn't heard of this use case yet.

Why would you need to change the `pathPrefix`? This should be handled by `node-github` I think, right?

**Comment by webpro** [comment]
This feature is sitting in a [branch](https://github.com/webpro/release-it/tree/github-host), waiting for v5 to be released. As this is a new feature, it will be in v5.1. Also see 746481a79e478fc80bbaff7ac98c9b9548fee6e4.

**Comment by webpro** [comment]
This has just been release in [v5.1.0](https://github.com/webpro/release-it/releases/tag/5.1.0)
