### ISSUE TITLE
Release to github

### ISSUE THREAD

**Issue by jameswilson** [webpro/release-it#17]
We're using npm command line scripts as a build tool for a private project on a private repo in GitHub where it doesn't make sense to release / publish to npm package registry.

Can the options somehow be configured to create a release on the *GitHub* repository,  and not be published to NPM? I wasn't able to grok this just reading the readme file. 

Thanks!

**Comment by webpro** [comment]
It checks the "private" setting in your package.json, and you can also use the "publish" option. Also see #16.

**Comment by jameswilson** [comment]
Thanks @webpro , so if I understand correctly, setting private to true would make it not be published at all?  I don' t necessarily want to do that.  I would like the publish feature to leverage the tag it created in the repository to publish a release to GitHub (instead of NPM package registry) using GitHub releases:

* https://github.com/blog/1547-release-your-software
* https://help.github.com/articles/creating-releases/
* https://developer.github.com/v3/repos/releases/

>  you can also use the "publish" option

It looks like the publish option is a boolean, and I couldn't find any example of how to use the publish option to send to GitHub instead of NPM package registry.  Can you point me to an example?  Thanks again.

**Comment by webpro** [comment]
If you set `"private": true` in your package.json, then npm will refuse to publish it.

Publishing to npm is a different thing compared to pushing a tag to GitHub. This project can tag commits and annotate the tag (i.e. a basic way to release a package on GH), but it does not have the feature to fully create a release, including a description, as described in https://help.github.com/articles/creating-releases/.

**Comment by webpro** [comment]
See for instance [this project's releases](https://github.com/webpro/release-it/releases) what you'd get.

**Comment by webpro** [comment]
Hi @jameswilson, you might be interested to hear that the feature we discussed is available.

**Comment by jameswilson** [comment]
@webpro, very cool!  Will check it out when I get a chance.  Thanks.
