### ISSUE TITLE
when including; "private: true' in execute, release hangs upon finishing 

### ISSUE THREAD

**Issue by takotuesday** [webpro/release-it#18]
Here is my release.execute call:
```
                release.execute({
                    buildCommand:   'npm install && npm run build && npm run ',
                    commitMessage:  'chore(release): v%s',
                    increment:      version,
                    pkgFiles:       'package.json',
                    private:        true,
                    tagAnnotation:  'Release v%s',
                    tagName:        'v%s',
                    verbose:        true
                }).finally(done);
            });
```
After running release, I am able to publish to git, and as expected I am not prompted to publish to npm. The problem is however, that the task hangs after 'Finished' and I must hit enter to end the procress. This doesnt happen when 'private' is not passed as an argument to execute.
```
[execute] git tag  --annotate --message="Release v4.0.8" v4.0.8
[?] Push? No
No Git endpoint provided for `distRepo` (distribution repository).
[16:35:27] Finished 'release' after 28 s
```

**Comment by webpro** [comment]
The first thing that comes to mind is that you probably need to exit the process in Node. See the CLI binary: https://github.com/webpro/release-it/blob/master/bin/release.js. Are you handling this in your `done` function? E.g.:

```js
release.execute({}).then(function() {
    process.exit(0);
}, function(error) {
    console.error(error);
    process.exit(1);
});
```

PS There might be a better way to do handle this using Inquirer, haven't looked into this for a while.

**Comment by webpro** [comment]
No reply, so closing this.
