### ISSUE TITLE
How to publish only files from /dist catalog in my repository via .release-it.json ?

### ISSUE THREAD

**Issue by darekf77** [webpro/release-it#186]
For now.. I need to `cd dist && release-it`. I just wanna publish generated 
`dist/` folder instead of whole repository. How can I do it ?

Thanks for any help.

**Comment by webpro** [comment]
It depends... But the simplest answer to your question would be:

```
{
  "npm": {
    "publishPath": "dist/",
  }
}
```

**Comment by darekf77** [comment]
OK perfect. Thanks.
