### ISSUE TITLE
Can't use it without package.json

### ISSUE THREAD

**Issue by AdrianSkierniewski** [webpro/release-it#189]
Hi,

I've recently updated my version of release-it and I started getting an error related to missing package.json file.
Here is exact line that causes this behavior: https://github.com/webpro/release-it/blob/master/lib/config.js#L64
Should new version of release-it work for non-npm projects too?

**Comment by webpro** [comment]
The error thrown for a missing `package.json` has two reasons:

* The `version` found in there is used as a fallback or initial version in case the git tag can't be found.
* It serves as an extra check to increase chances that the user is in the root directory of the project (which is relevant to executing build commands etc).

However, I agree that it should be possible to use this tool without that file. I'll keep this ticket open until this is resolved.

In the meantime, you could use a dummy (`{}`) `package.json` in your project.

**Comment by webpro** [comment]
Released in [6.0.0-rc.0](https://github.com/webpro/release-it/releases/tag/6.0.0-rc.0). You can install with `npm install release-it@rc`.

**Comment by AdrianSkierniewski** [comment]
@webpro Thank you! :)

**Comment by ilaipx** [comment]
version 9.3.0 still fails when I don't have `package.json` even with an existing tag, any reason why?

**Comment by webpro** [comment]
Are you using `pkgFiles: null` or `--no-pkgFiles`? Otherwise it's still trying to bump these files.
