### ISSUE TITLE
Support for Maven (SNAPSHOT) versioning

### ISSUE THREAD

**Issue by erikgb** [webpro/release-it#19]
##### First some background
We are in the process of introducing proper versioning, including releasing, to our Grunt build. Our Grunt build is producing a common "style guide" - used by various in-house developed applications (both Java and .Net). Mostly I work with Java, and use Maven for build and dependency management. From our Java applications, the "style guide" is embedded using [WebJars](http://www.webjars.org/) pulled down from our internal [Nexus](http://www.sonatype.org/nexus/).
Until now, we have had no proper versioning of the Grunt build (just a hard-coded default version). For versioning and deployment to Nexus, we have a Maven build wrapper around the Grunt build, using standard Maven versioning in the build wrapper (pom.xml).

##### What we would like to do
We want to establish a common versioning and release process that is satisfactory for all stakeholders in the ""style guide" (both Java and .Net developers). Ideally, we would like to have the versioning and release process defined for Grunt, and get rid of the Maven build wrapper. In the process of investigating how to do this properly, I came accross *release-it*.

##### The problem
I have been doing some prototyping, and currently it seems to be impossible to use [Maven versioning](http://docs.codehaus.org/display/MAVEN/Versioning) with *release-it*. In particular, the notion of a SNAPSHOT version (pre release version) seems hard to achieve. 

##### My wish
Some way to configure *release-it* to work more or less as the [maven-release-plugin](http://maven.apache.org/maven-release/maven-release-plugin/) when it comes down to versioning and Git commits/tags. I particular:
* Always a SNAPSHOT version in HEAD of branch
* Two commits per release
 * First commit for the release tag
 * Second commit for setting the next development version

**Comment by webpro** [comment]
Hi @erikgb, I think I mostly get what you want to achieve, but could you please make it more detailed by  describing the steps roughly in Git commands?

**Comment by erikgb** [comment]
Thanks for your feedback, @webpro! 
I will try to explain in a little more detail - especially the git commands:

Let us assume that we want to release version 2.0.0 of our artifact. The current version in HEAD of branch will then probably be something like 2.0.0-SNAPSHOT.

1. Check for local modification: `git status`
1. Modify version to release version (2.0.0) in applicable files and commit changes: `git commit -m 'prepare release 2.0.0' <modified files>`
1. Tag release commit: `git tag 2.0.0`
1. Modify version to next development version (i.e. 2.0.1-SNAPSHOT) in applicable files and commit changes: `git commit -m 'prepare for next development iteration'`

The release version of the artifact should (of course) be built from the release tag (`2.0.0` in our simple example).

Please let me know if you need additional details or clarifications. I will be happy to contribute with any valuable input.

**Comment by webpro** [comment]
So you it's one complete release phase for `2.0.0` (steps 1-3), and then one extra commit for `2.0.1-SNAPSHOT` (step 4)?

So your question is whether this tool could support that one extra versioning + commit step?

**Comment by erikgb** [comment]
Correct! I tried to use this tool to release a SNAPSHOT-version, and it worked more or less. Based on the version being 2.0.0-SNAPSHOT in HEAD of branch, the tool released version 2.0.0 and set the tag correctly. But the "next development" version was set to 2.0.1 - which is obviously wrong when using the Maven versioning regime.

**Comment by webpro** [comment]
Maybe you want another semver indicator like "major" or "patch" (e.g. "snapshot" or something) for this specific pattern, right? Not sure if I like this. But given that the current version is `2.0.0`, you could then just release `2.0.1-SNAPSHOT` by specifying this exact version?

**Comment by erikgb** [comment]
You never **release** a SNAPSHOT version. A SNAPSHOT version is a version under development. See [this post](http://stackoverflow.com/questions/5901378/what-exactly-is-a-maven-snapshot-and-why-do-we-need-it) for an (more or less correct) explanation of SNAPSHOT versions.

A SNAPSHOT version gives the version (alone) the semantic meaning of being a _version under development_ (_'an unstable reference to a moving target'_). On the contrary, a non-SNAPSHOT version is a build that will never change. I.e. version 2.0.0 will always be the same - regardless on when (or how) you got it.

With the current behavior of this tool, it seems like any version could in fact be considered a moving target. There is no notion of a _version under development_, and you would have to consider the build number (or something similar) to determine your **exact** version. A small disclaimer, so you don't get offended in any sense: I do not necessarily consider this a bad practice, it is just not compatible with Maven versioning. ;-)

**Comment by webpro** [comment]
I understand, I should've said "you could then just *commit* `2.0.1-SNAPSHOT`" indeed. I mean, you can commit and not actually release with this tool.

**Comment by webpro** [comment]
@erikgb, feel free to reopen this if you'd like to discuss things further. But I'm closing this for now.
