### ISSUE TITLE
non-interactive:true in .release-it.json overridden by is-ci

### ISSUE THREAD

**Issue by limenet** [webpro/release-it#190]
Hi there,

First of all, thank you for providing this great package, it has simplified releasing new versions a lot for me and I really like the JSON config file to automate releasing a new version even more.

My config is fairly basic, but a crucial feature for me is `"non-interactive": true` as it allows me to simply type `release-it` and hit Enter. Some time ago, I noticed this setting was ignored, yet the config file was still being read and interpreted correctly -- except for the non-interactive flag. Contents of `.release-it.json`:

```json
{
  "non-interactive": true,
  "pkgFiles": ["package.json", "composer.json"],
  "npm": {
    "publish": false
  },
  "github": {
    "release": false
  },
  "dist": {
    "repo": false
  }
}

```

After looking at the code, I found the location where the options (default, file, CLI arguments etc.) are being merged.:

```js
  mergeOptions(options) {
    return _.defaultsDeep(
      {},
      this.cliArguments,
      options,
      {
        'non-interactive': isCI
      },
      this.localOptions,
      {
        name: this.npm.name || path.basename(process.cwd()),
        npm: this.npm
      },
      this.defaultOptions
    );
  }
```

When executing this function on a non-CI machine, this results in `'non-interactive': isCI` overriding `this.localOptions,`. This change seems to have been introduced in https://github.com/webpro/release-it/commit/ecef437d276814a488cae570110d94e51b841ae0#diff-f7bf2b665273dfa66ffa4ad7c0a52bb9R104

---

**Steps to reproduce:**

1. Create `.release-it.json` with `{"non-interactive": true}`
1. Run `release-it` on a non-CI machine

**Expected behavior:**
1. Next version is automatically created/pushed/released etc. without any user interaction required

**Actual behavior:**
1. Question "? Ready to release X? (Y/n)" is asked and has to be answered
1. Same applies to all further questions

I'm using version 5.1.2 (current stable) on Windows 10 x64 and Node.js 9.3.0 with Yarn 1.3.2. As the code in question has not been modified since the release of 5.1.2 I did not try to reproduce the bug on newer, pre-release versions.

I think this issue could be solved by rewriting `mergeOptions()` as follows (untested and not elegant):

```js
  mergeOptions(options) {
    let merged = _.defaultsDeep(
      {},
      this.cliArguments,
      options,
    );

    if (isCI) {
      merged = _.defaultsDeep(
        merged,
        {
          'non-interactive': true
        }
      );
    }

    merged = _.defaultsDeep(
      merged,
      this.localOptions,
      {
        name: this.npm.name || path.basename(process.cwd()),
        npm: this.npm
      },
      this.defaultOptions
    );

    return merged
  }
```

If you'd like me to, I can create a pull request.

Please let me know what you think and if I can help you with anything!

**Comment by webpro** [comment]
Thanks for the catch & bug report! I think I've got an easy fix in [v5.1.3](https://github.com/webpro/release-it/releases/tag/5.1.3). Please let me know whether it works for you :-)

**Comment by limenet** [comment]
Thank you very much @webpro , I really appreciate you fixing this so quickly and releasing it! Your fix (I love its simplicity, especially compared to my poor approach) works perfectly!

**Comment by webpro** [comment]
You're welcome. Thanks again & happy releasing!
