### ISSUE TITLE
[Feature request] Export commit messages to text file

### ISSUE THREAD

**Issue by Kristinita** [webpro/release-it#200]
### 1. Request

It would be nice, if would be possible export commit messages for release to text file.

### 2. Justification

Developers of [**Sublime Text 3**](https://www.sublimetext.com/3) packages needs to add [**release messages**](https://packagecontrol.io/docs/messaging), that can be seen by users.

I create text files from commit messages, but now I do it manually. It may take a lot of time. I don't find, how I can create these text files automatically.

### 3. Example configuration

For example, my previous version of Sublime Text package — `0.0.1`. I commit and push 2 changes:

+ `git commit -m "[Add] New feature"`
+ `git commit -m "[Add] Another feature"`

Now I want to create `0.0.2` version. I create new release use release-it.

Also I need to create in folder `messages` file `0.0.2.txt`. I write to this file my commit messages. My `0.0.2.txt` file for example:

```markdown
+ [Add] New feature
+ [Add] Another feature
```

**But** I need to create `0.0.2.txt` file manually. It would be nice, if would be possible generate it automatically.

See structure of real project in my [**SashaSublime**](https://github.com/Kristinita/SashaSublime) repository.

### 4. Expected behavior

__For example__, __if__ my `.release-it.json` file:

```json
{
  "src": {
    "tagName": "st3-%s"
  },
  "github": {
    "release": true,
    "tokenRef": "GITHUB_TOKEN",
    "export_to_file": true,
    "export_folder": "messages"
  }
}
```

and I print in command-line:

    release-it --export-to-file

File `<new_version>.txt` to create in my `messages` folder. It will contain commits description from previous to new release of project.

Thanks.

**Comment by webpro** [comment]
Thanks, @Kristinita. For that, I have a different solution in mind, which is hopefully even more flexible. It would look something like this:

```
{
  "src": {
    "afterReleaseCommand": "echo \"${changelog}\" > changelog-v${version}.txt"
  }
}
```

Alternatively, you could use the `buildCommand`. What do you think?

You can already use options like `src.tagName` and `version` in commands, but `changelog` isn't available yet. I'm now planning to add this in v6.1, after the v6.0 release (shortly).

**Comment by Kristinita** [comment]
Thanks! Nice idea!

Only I need push `<new_version>.txt` file to GitHub before release creating. So is would be nice to have `beforeReleaseCommand`.

Thanks.

**Comment by webpro** [comment]
The tool exposes `latestVersion` and `version`, so I think the latter is what you need here.

**Comment by webpro** [comment]
Ticket #200 inspired the 100th release ([6.1.0](https://github.com/webpro/release-it/releases/tag/6.1.0))! 🎉

**Comment by Kristinita** [comment]
@webpro, thanks, it works!

But is it possible get permalinks to commits from `changelog` variable?

For example, part of my `.release-it.json` file:

```json
"buildCommand": "echo ${changelog} > \"messages\/${version}.txt\""
```

Build `<version>.txt` file:

```markdown
Commit message (3fff1f2)
```

Expected:

```markdown
Commit message [3fff1f2](https://github.com/Kristinita/SashaReleaseItTesting/commit/3fff1f24c2bbb9b46a16e55ac53b531d0851413b)
```

Thanks.

**Comment by webpro** [comment]
You would have to override the `changelogCommand` for this; looks feasible.
