### ISSUE TITLE
Unable to bump pkgFiles if they are different files for source and dist repo

### ISSUE THREAD

**Issue by Necroskillz** [webpro/release-it#21]
Hi,
I only have `package.json` in the source repo, and only `bower.json` in the dist repo. I would like to update both, but with
```
    "pkgFiles": ["package.json", "bower.json"],
```
i get

```
WARNING There was a problem bumping the version in bower.json
ERROR fatal: pathspec 'bower.json' did not match any files
```
Either it needs to not throw an error if the file is not found, or i would need something like `"distPkgFiles"`. It could also be regex or glob patter. What do u think?

Thx

**Comment by webpro** [comment]
Agreed, a warning should be sufficient. Will look into it later today.
