### ISSUE TITLE
[Question] Required scopes

### ISSUE THREAD

**Issue by Kristinita** [webpro/release-it#215]
### 1. Summary

I don't find, which scopes I need select, when I create GitHub token, that release-it works correct.

### 2. Details

I read [**this item**](https://github.com/webpro/release-it#%EF%B8%8F-github-release) of release-it documentation:

> Obtain a GitHub access token.

> Make sure the token is available as an environment variable. Example:

I don't find, which scopes I need to select.

I select all:

![Scopes](https://i.imgur.com/z4fQrOE.png)

Can I not select some of these scopes?

Thanks.

**Comment by webpro** [comment]
You only need the first category ("repo"), release-it doesn't need more rights. I've added this to the readme, thanks!
