### ISSUE TITLE
[Question] Variables list

### ISSUE THREAD

**Issue by Kristinita** [webpro/release-it#216]
### 1. Summary

I don't find list of variables, that I can use in `.release-it.json` file.

### 2. Example

For example, I want to add variable — URL of current remote repository.

That it works like this:

```json
"buildCommand": "changelog ${version} -u ${remote.origin.url} -f -"
```

**But** I don't find, which variable I need to use instead of `${remote.origin.url}`.

### 3. Did not help

I don't find list of available variables in:

1. release-it documentation,
1. [**external links**](https://www.npmjs.com/package/release-it#-resources) in release-it documentation,
1. issues of this repository.

Thanks.

**Comment by webpro** [comment]
This is exposed:

* everything in https://github.com/webpro/release-it/blob/master/conf/release-it.json
* plus `version`, `latestVersion` and `changelog`

If you start with `--debug` then it first prints the full parsed configuration object.

Added to the readme, thanks!

**Comment by Kristinita** [comment]
@webpro, thanks, I looked into this file. Did I understand correctly that there is no variable for the URL of the current remote repository?

It would be nice, if users doesn't need to add value of this variable for each repository.

Thanks.

**Comment by webpro** [comment]
You could do something like this to get it on the fly:

```
"buildCommand": "changelog ${version} -u $(git config --get remote.origin.url) -f -"
```

**Comment by Kristinita** [comment]
@webpro , I'm sorry, `$(git config --get remote.origin.url)` doesn't transform to real URL for me.

```bash
D:\SashaBranchReleaseIt>git config --get remote.origin.url
https://github.com/Kristinita/SashaBranchReleaseIt.git

D:\SashaBranchReleaseIt>release-it --no-npm.publish -n -V
$ git rev-parse --git-dir
.git
$ git config --get remote.origin.url
https://github.com/Kristinita/SashaBranchReleaseIt.git
$ git diff-index --name-only HEAD --exit-code
$ git rev-parse --abbrev-ref --symbolic-full-name @{u}
origin/master
$ git describe --tags --abbrev=0
st3-1.0.21
$ bump package.json 1.0.27
$ changelog 1.0.27 -f -
#### 1.0.27 (2018-01-25)

##### Build System / Dependencies

* **release-it:**
  *  Command-line variable in build command (acef94a4)
  *  Desable -f (cdad4385)
  *  Curly braces not round again (b0b54cad)
  *  Curly braces, not round (6801469a)
  *  Test variable, that I get from command line (26a0f23b)
* **Test variable from command line in build command:**  buildCommand, not changelogCommand (72157be8)


$ changelog 1.0.27 -u $(git config --get remote.origin.url)

node  "C:\Users\SashaChernykh\AppData\Roaming\npm\\node_modules\generate-changelog\bin\generate" 1.0.27 -u $(git config --get remote.origin.url)

ERROR
```

Also I try:

+ curly braces instead of round,
+ disable `-f` and `-` arguments.

Thanks.

**Comment by Kristinita** [comment]
@webpro , assign output of a program to variable is possible ([**Windows example**](https://stackoverflow.com/a/2340018/5951529)), but I don't find cross-platform solution.

It would be nice, if you:

+ say cross-platform solution;
+ or add ${remoteurl} variable.

Thanks.

**Comment by webpro** [comment]
Support for the content of custom commands (including cross-OS solutions) would be out of scope for this project.

However, adding some of the `repo` information is probably a convenient addition indeed.

**Comment by webpro** [comment]
@Kristinita, I've added the `repo` object to use in custom commands in [v6.2.0](https://github.com/webpro/release-it/releases/tag/6.2.0)

**Comment by Kristinita** [comment]
@webpro,

### 1. Question

Is any way to remove `.git` ending from `${repo.remote}`, use cross-platform syntax?

### 2. buildCommand

Example part of my `.release-it.json` file:

```json
"buildCommand": "changelog -u ${repo.remote} -f Changelog.md"
```

### 3. Steps to reproduce

I run:

    release-it --no-npm.publish -n -V

### 4. Expected behavior

Part of output:

```bash
$ changelog -u https://github.com/Kristinita/SashaBranchReleaseIt -f Changelog.md
```

### 5. Actual behavior

```bash
$ changelog -u https://github.com/Kristinita/SashaBranchReleaseIt.git -f Changelog.md
```

If `.git` on end of link, changelog command will work incorrect.

### 6. Not helped

1. Yes, I can remove `.git`, use, for example, `sed` command and add output as variable. But, possibly, I can't use cross-platform syntax; see [**my question**](https://unix.stackexchange.com/q/420742/237999) in Unix Stack Exchange site.

Thanks.

**Comment by webpro** [comment]
I think there are two options:

1. The `remoteUrl` is resolved with `git config --get remote.origin.url` so you can configure the Git repo remote itself to not contain `.git`.
2. You could use something like `https://${repo.host}/${repo.repository}`

**Comment by Kristinita** [comment]
Thank you!

**Comment by Kristinita** [comment]
@webpro, It would be nice add to documentation, that [**variables**](https://github.com/release-it/release-it#hooks) instead of `${version}` now works only for hooks. For example, this code:

```yaml
git:
  changelog: changelog -f - u - https://${repo.host}/${repo.repository}
```

Will not work currently. I get an error:

```text
ERROR repo is not defined
```

Thanks.
