### ISSUE TITLE
config from .release.json is being overriden by command line arguments that were not specified

### ISSUE THREAD

**Issue by Necroskillz** [webpro/release-it#22]
Because command line arguments have highest priority, and optimist.boolean initializes all args to false. So all booleans in .release.json that also can be specified on the command line have no effect.

```
> release-it.cmd minor --dry-run
{ _: [ 'minor' ],
  d: true,
  'dry-run': true,
  e: false,
  debug: false,
  f: false,
  force: false,
  h: false,
  help: false,
  n: false,
  'non-interactive': false,
  p: false,
  publish: false,
  v: false,
  version: false,
  V: false,
  verbose: false,
  '$0': 'node C:\\Users\\necros\\AppData\\Roaming\\npm\\node_modules\\release-it\\bin\\release.js',
  i: 'minor',
  increment: 'minor',
  commitMessage: undefined }
```

**Comment by webpro** [comment]
Thanks for the bug reports and PR, @Necroskillz!

I've kind of fixed this issue, but e.g. `--no-verbose` still doesn't work with this work-around. But at least regular command line options override other options again.

**Comment by webpro** [comment]
Release as v0.0.17

**Comment by Necroskillz** [comment]
If u replace (anyway obsolete) optimist with https://www.npmjs.com/package/yargs, you can specify default for boolean, that would be a better solution,

```
require('yargs')
    .boolean('bla')
    .alias('b', 'bla')
    .default('bla', undefined)
    .argv
```

now you know for sure if its true/false of if it wasn't specified.

**Comment by webpro** [comment]
Yes, I should replace optimist indeed. Maybe later :-)

**Comment by Necroskillz** [comment]
I will create a new issue for u, so u don't forget. Thx for the fast fixes :+1:
