### ISSUE TITLE
"EISDIR: illegal operation on a directory, read" while publishing to a dist 

### ISSUE THREAD

**Issue by elpdrc** [webpro/release-it#221]
Case: 
- My build phase uses ng-packagr to create from an angular project a 'dist' folder containing not only files but sub folders.
- When running release-it with `dist` option, I get this error. 

```
ERROR Cannot copy from `/home/circleci/repo/dist/bundles` to `/home/circleci/repo/.stage/bundles`: Cannot read from `/home/circleci/repo/dist/bundles`: EISDIR: illegal operation on a directory, read
```

I think this is coming from the usage of the `cpy` package to copy files from `dist` to `stage`.
https://github.com/webpro/release-it/blob/master/lib/shell.js#L96

The `cpy` package does not support copying directories.
https://github.com/sindresorhus/cpy/issues/40

**Comment by webpro** [comment]
Thanks @elpdrc , good catch. I've fixed this in [v6.2.0](https://github.com/webpro/release-it/releases/tag/6.2.0). Directories should no longer throw, and those containing targeted files should be copied.
