### ISSUE TITLE
Documentation or pointers in using release-it in javascript (node 8)

### ISSUE THREAD

**Issue by appsolutegeek** [webpro/release-it#224]
Hi,

After reading the issues it appears that it is supported to call the release-it in javascript using node v8 or later.

Could anyone let me know some further info, any documentation?

I saw this in the issues, anything else I can do ?

Or is it a case of looking inside the javascript file ?

I presume this is the same package as the cli ?

const ReleaseIt = require("release-it").default

```
ReleaseIt({
  "non-interactive": true,
  npm: {
    publish: false
  }
}).then(…)
```

Thanks in advance

**Comment by webpro** [comment]
Yes, this is an undocumented feature indeed. Feel free to use it though, I'll document it shortly.

For now, this is the object the promise resolves with when release-it is done: https://github.com/webpro/release-it/blob/c6d079f7d6bce287b6bf5b48dbf250ab6aed27c8/lib/tasks.js#L213-L217

I'll keep this issue open until it is documented.
