### ISSUE TITLE
Can I customize the commit messages?

### ISSUE THREAD

**Issue by yeikel** [webpro/release-it#227]
I read the docs, but I did not see any information about the topic. 

Can I customize the git commit message?  In my use case, I would like to set a specific text along the desired version instead of the generic "Release xxx". For example, "[Release] xxx"

I am looking for a configuration option that would allow me to do this rather than to change the code for my needs. 

Thank you.

**Comment by webpro** [comment]
Hi @yeikel! Yes, there are two ways to configure the commit message:

1. Use e.g. `--src.commitMessage="[Release] v%s"` from the command line.
2. Set `"commitMessage": "[Release] v%s"` in the `"src"` section of `.release-it.json` (put this file in the root of the project).

Here is the default setting: https://github.com/webpro/release-it/blob/c6d079f7d6bce287b6bf5b48dbf250ab6aed27c8/conf/release-it.json#L17

**Comment by yeikel** [comment]
That worked. Thank you
