### ISSUE TITLE
Using with npm scripts fails

### ISSUE THREAD

**Issue by cristobal-io** [webpro/release-it#229]
Included in a project with npm scripts like the following:

```
scripts: {
  "prerelease": "npm run build",
 "release": "release-it"
}
```

If I run it directly on the terminal like `release-it` it works properly, but if I run it from the scripts with `npm run release` it is causing the following error:
```
ERROR Working dir must be clean.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

I checked and the git status is clean and everything has been pushed, and doing it directly on the terminal always works, even if I do the steps the npm script does, building first and without doing anything else doing `release-it`

**Comment by webpro** [comment]
I guess `npm run build` causes local changes and, on behalve of release-it, Git says "Working dir must be clean". Not sure about the difference if you run the scripts manually, though.

You could try these options:

1. Add the output dir/files to `.gitignore`
2. Set `requireCleanWorkingDir: false` in the `.release-it.json` config (or from command-line: `--no-requireCleanWorkingDir`)

**Comment by cristobal-io** [comment]
That worked!

I updated the command with the flag `--no-requireCleanWorkingDir` I have the dist folder being published, so I don't want to add it to `.gitignore`

It was strange because, after the error, git status was clean, and before running `npm run release` I was running `npm run build` so nothing was changed.

However, thanks for the quick response and solution.

Closing the issue.

**Comment by webpro** [comment]
Cool. You can also use `--verbose` which might give some useful hints in such cases. Good luck!

**Comment by pixelastic** [comment]
I had a similar issue, so for the sake of helping fellow developers, here is more information:

- I ran a `build` script before my release
- The `build` script was regenerating a `json` file
- In that case, the `json` content was the same between each build
- Somehow, `release-it` was refusing to release, telling me my repository was unclean
- A manual `git status` showed that everything was ok
- After digging in the code, I found that the call to `git diff-index --quiet HEAD --` done by `release-it` was actually returning changed files
- My `json` file was reported as having changed, even if its content was exactly the same
- I tried to add some `sleep` between my `json` generation and the call to `release-it`, but it didn't fixed it
- **What fixed it was to make a call to `git status` after the `build` step but before the `release-it` step**
- Somehow it forced git to see that the file, even if updated, was actually the same as before and not treat the repo as dirty

Hope that helps someone, someday :)

**Comment by Michael77** [comment]
@pixelastic this fixed it for me! Thank you!

**Comment by YOEL311** [comment]
this command works for me

``yarn release  --no-git.requireCleanWorkingDir``

but this 

``yarn release --no-requireCleanWorkingDir``

not work

**Comment by webpro** [comment]
```
git diff-index --quiet HEAD
```

Not sure why Git thinks the file has changed. I remember having this issue myself too.

Good to know a `git status` apparently refreshes the index.


> this command works for me
> 
> `yarn release --no-git.requireCleanWorkingDir`
> 
> but this
> 
> `yarn release --no-requireCleanWorkingDir`
> 
> not work

That's expected, as documented. Any option in https://github.com/release-it/release-it/blob/main/config/release-it.json can be set with this dot notation (and negated using `--no-`).
