### ISSUE TITLE
a release will commit previously untracked files

### ISSUE THREAD

**Issue by MichaelMure** [webpro/release-it#230]
For those of us that sometimes keep untracked files in the repository, the silent commit and push of previously untracked files could be a bad surprise.

If the goal is to commit the package.json files, why not select them manually, or at least limit the commit to previously tracked files ?

**Comment by webpro** [comment]
Good point, that's indeed probably a good idea in most cases.

It's also a good idea to have such files/dirs listed in `.gitignore`, right?

**Comment by MichaelMure** [comment]
`.gitignore` is not always a practical solution. Currently I have in my repository some untracked files:
- some code experiments in untracked files that I keep around until I do something better with them
- some design document, temporary files to keep some copy paste at hand ...

Those files don't need to be in the `.gitignore` and confuse other peoples working on the repo. Commiting and pushing them is a mistake and should not happen, especially silently.

**Comment by webpro** [comment]
I've made the change and released [v7.0.0](https://github.com/webpro/release-it/releases/tag/7.0.0). Thanks!

**Comment by MichaelMure** [comment]
Thank you !
