### ISSUE TITLE
[Bug] buildCommand works in 6.2.0, but not in 7.0.2 version

### ISSUE THREAD

**Issue by Kristinita** [webpro/release-it#233]
### 1. Summary

Same `buildCommand` successful works for me for 6.2.0 version, but doesn't work for 7.0.2 version.

### 2. Environment

+ see my environment [**here**](http://kristinita.ru/IT-articles/Fastest-way-to-add-new-version-of-Sublime-Text-3-package#testing-environment),
+ [**my example `.release-it.json`**](https://github.com/Kristinita/SashaBranchReleaseIt/blob/master/.release-it.json), see [**here**](http://kristinita.ru/IT-articles/Fastest-way-to-add-new-version-of-Sublime-Text-3-package#release-itjson-1), what makes lines in my `.release-it.json`.

```json
{
    "buildCommand": "changelog -f - -u https:\/\/${repo.host}\/${repo.repository} | tee messages\/${version}.txt | cat - Changelog.md > temp && mv temp Changelog.md",
    "changelogCommand": "changelog -f -",
    "github": {
        "release": true,
        "tokenRef": "GITHUB_TOKEN"
    },
    "npm": {
        "publish": false
    },
    "safeBump": false
}
```

### 3. Steps to reproduce

+ I make any changes in my repository,
+ `git add .`,
+ `git commit -m "Any changes"`,
+ `git push`,
+ `release-it -n`.

### 4. 6.2.0 behavior

**If** release-it=6.2.0, `messages/${version}` file [**successful create**](https://github.com/Kristinita/SashaBranchReleaseIt/commit/a09353797c099b73b7099e109631219fea29792e).

It expected behavior for me.

### 5. 7.0.2 behavior

**If** release-it=7.0.2, `messages/${version}` file [**doesn't create**](https://github.com/Kristinita/SashaBranchReleaseIt/commit/4faff51c1402202e5c7f9c93532ae020102a3608).

Thanks.

**Comment by webpro** [comment]
There was a [breaking change in v7](https://github.com/webpro/release-it/blob/master/CHANGELOG.md), release-it no longer adds untracked files to the release commit (discussed in #230).

For now, you could downgrade to v6.x, or move the changelog into a single, tracked file.

I'm a bit on the fence whether to add something of a `addUntrackedFiles` option to opt-in to the previous behavior, as I think that's not a best practice. Happy to hear any thoughts.

**Comment by Kristinita** [comment]
@webpro, maybe:

If `addUntrackedFiles = True`,

    untracked files behavior as 6.2.0 version.

else:

    untracked files behavior as 7.x.x version.

Thanks.

**Comment by Kristinita** [comment]
@webpro , any ideas?

I don't think, that downgrade is a best idea.

Thanks.

**Comment by webpro** [comment]
You could add something like `git add messages/${version}.txt` to a command to make sure a file gets added to a release commit.

**Comment by webpro** [comment]
I've added `src.addUntrackedFiles` to the configuration options in [v7.3.0](https://github.com/webpro/release-it/releases/tag/7.3.0).
