### ISSUE TITLE
Minor problem in releases

### ISSUE THREAD

**Issue by posva** [webpro/release-it#234]
Hello!
I was looking at the releases and the release 7.0.1 seems to contain every commit in it (not just the difference between 7.0.1 and 7.0.0). Just letting you know in case you want to manually remove it!

Thanks a lot for creating release-it, it saves so much time! ❤️

**Comment by webpro** [comment]
Thanks, @posva! Not sure what happened, I think I did the GH releases in the wrong order or something. Anyway, fixed.
