### ISSUE TITLE
Unable to load the "angular" preset package (v7.1.0)

### ISSUE THREAD

**Issue by justerest** [webpro/release-it#250]
```bash
$ release-it 
ERROR Unable to load the "angular" preset package. Please make sure it's installed.
```

.release-it.json
```json
{
  "increment": "conventional:angular",
  "beforeChangelogCommand": "conventional-changelog -p angular -i CHANGELOG.md -s -r 0",
  "changelogCommand": "conventional-changelog | tail -n +3",
  "safeBump": false,
  "github": {
    "release": true
  },
  "src": {
    "tagName": "v%s"
  }
}
```

This config file good worked with older versions (example: v7.0.2).

NOTE: My project is not Angular

__release-it__ package is installed as global.
Linux justerest-pc 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

**Comment by webpro** [comment]
Thanks, @justerest! Should be fixed with [v7.2.0](https://github.com/webpro/release-it/releases/tag/7.2.0).
