### ISSUE TITLE
Failed when pushed or PR-merged on Travis CI

### ISSUE THREAD

**Issue by 1natsu172** [webpro/release-it#253]
Hi, @webpro . 

I am trying to use release-it from Travis CI at PR-merged. But release-it doesn't work on TravisCI because it has forced check out to commit(`git checkout -qf <commit-hash>`) internally after merging PullRequest.

Since this is in the state of detached HEAD, it's an error in the processing of `git rev-parse - abbrev-ref - symbolic-full-name @ {u}`(function of release-it/lib/git.js) .

## Logs

Partial log of TravisCI's Git repository processing

```bash
$ git clone --depth=50 --branch=master https://github.com/1natsu172/Outside-YouTube-Player-Bar.git 1natsu172/Outside-YouTube-Player-Bar
Cloning into '1natsu172/Outside-YouTube-Player-Bar'...
$ cd 1natsu172/Outside-YouTube-Player-Bar
$ git checkout -qf ca64801febe8722d9532243f1bb964365fc47b27
```

Partial log of release-it

```bash
Deploying application
yarn run v1.3.2
$ release-it -n
$ git rev-parse --git-dir
.git
$ git config --get remote.origin.url
https://github.com/1natsu172/Outside-YouTube-Player-Bar.git
$ git diff-index --name-only HEAD --exit-code
$ git rev-parse --abbrev-ref --symbolic-full-name @{u}
fatal: HEAD does not point to a branch
ERROR No upstream configured for current branch.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Script failed with status 1
failed to deploy
```

## Usage on CI?

Even if you could get the branch name in detached HEAD state, I think that git push can not be done.

You used travisCI in the repository of release-it. So I thought that it could be used. (There is also a `release-it -n` command in README...).  Am I making a fundamental mistake? Or is there any other setting for use with CI?

**Comment by webpro** [comment]
Hi @1natsu172! This is indeed an issue when travis does that.

* Without an upstream, `--no-requireUpstream` would add `--set-upstream origin [current-branch]` when pushing. But in this case (clone from `master`) that would not be necessary.
* Not very elegant, but you could configure `src.beforeStartCommand` to something like `"git checkout master"` (or `--src.beforeStartCommand='git checkout master'` from the command line).

Let me know if that helps.

**Comment by 1natsu172** [comment]
It's not elegant but it worked if I checkout to `master` with the `src.beforeStartCommand` hook! 🎉 

Thanks for helps & this tool 👍
