### ISSUE TITLE
rollback feature ⏱

### ISSUE THREAD

**Issue by philippefutureboy** [webpro/release-it#262]
Hey!

I was wondering if you would consider having a rollback feature – i.e. one that rolls back if the process crashes midway (for instance npm credentials fail, but everything else has been pushed). I think it would be a great addition to release-it :)

Cheers ✨

**Comment by webpro** [comment]
Hi @philippefutureboy! That would definitely be cool.

It's not trivial, however. For instance, release-it would have to "change history" of a Git repository, and this is pretty risky imho (e.g. remove tag, revert to the correct commit).

In your example, one could still `npm publish` manually. I'd rather do this manually, depending on the issue at hand. Still, feel free to explore this idea further and I'm happy to consider a PR to add this feature.

**Comment by philippefutureboy** [comment]
True it is not a trivial matter to implement. However I don't see it to be overly complex either. I don't have a lot of time, but I'll check what I can do in the next few weeks to contribute to the feature. 

In the meantime if you suddenly have a strong urge to implement the feature, don't wait for me 😛
