### ISSUE TITLE
release-it can't find .release-it.json

### ISSUE THREAD

**Issue by MichaelMure** [webpro/release-it#263]
> $ GITHUB_TOKEN=.... release-it minor
> /usr/local/lib/node_modules/release-it/lib/config.js:37
>       throw new Error(`File not found: ${localOptionsPath}`);
>       ^
> 
> Error: File not found: /home/michael/dev/arbore/.release-it.json
>     at getLocalOptions (/usr/local/lib/node_modules/release-it/lib/config.js:35:13)
>     at new Config (/usr/local/lib/node_modules/release-it/lib/config.js:61:25)
>     at Object.<anonymous> (/usr/local/lib/node_modules/release-it/lib/config.js:165:25)
>     at Module._compile (module.js:641:30)
>     at loader (/usr/local/lib/node_modules/release-it/node_modules/babel-register/lib/node.js:144:5)
>     at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/release-it/node_modules/babel-register/lib/node.js:154:7)
>     at Module.load (module.js:560:32)
>     at tryModuleLoad (module.js:503:12)
>     at Function.Module._load (module.js:495:3)
>     at Module.require (module.js:585:17)
> 
> $ ls -l /home/michael/dev/arbore/.release-it.json
> -rw-r--r-- 1 michael michael 439 févr. 26 19:32 /home/michael/dev/arbore/.release-it.json

Release-it complains that the config file doesn't exist when it actually exist.

It happens with v7.2.1, v6.0.0 but not with v2.8.0.
On linux debian.
Node v7.7.2 and v9.2.1

**Comment by webpro** [comment]
Probably the file is invalid JSON. Can you please double-check?

**Comment by MichaelMure** [comment]
That was indeed an invalid json (a comma too much).

Maybe a message less misleading would be helpful.
