### ISSUE TITLE
[Feature] Gitlab integration

### ISSUE THREAD

**Issue by DanielRamosAcosta** [webpro/release-it#266]
It would be awesome a Gitlab integration.

**Comment by webpro** [comment]
Hi @DanielRamosAcosta! This tool should work with any Git repository.

Personally, I don't work with Gitlab. Are you referring to a specific feature, such as GitHub Releases, to work in a similar fashion with Gitlab?

**Comment by DanielRamosAcosta** [comment]
Yes, I was thinking about the Releases and assets upload.

**Comment by webpro** [comment]
Feel free to open a PR and explore this idea further. I'm interested as well.

**Comment by DanielRamosAcosta** [comment]
I'll look into it, thanks!

**Comment by webpro** [comment]
@DanielRamosAcosta Getting there: https://github.com/webpro/release-it#gitlab-releases
