### ISSUE TITLE
Committing untracked files to a dist release

### ISSUE THREAD

**Issue by colinkahn** [webpro/release-it#268]
I've found this change and was wondering if there is a way to replicate the old behavior?

https://github.com/webpro/release-it/commit/3454a017f1cd5ea5ef98ec5655f7ad0286357c58#diff-89fd8e8ef20565f129343f363cc8433cR49

I'm pushing up releases to a github distribution repository and while it is copying my dist files to .stage is says there is nothing to commit since they're not tracked.

Thanks!

**Comment by webpro** [comment]
Hi @colinkahn, thanks for the report. I've added `src.addUntrackedFiles` to the configuration options in [v7.3.0](https://github.com/webpro/release-it/releases/tag/7.3.0).

**Comment by colinkahn** [comment]
Awesome! Thanks 👍
