### ISSUE TITLE
Incorrect bump of file version

### ISSUE THREAD

**Issue by IamTheHttp** [webpro/release-it#270]
Hey,

using version 7.2.1

When using "release-it" (as a command) I'd expect the patch to be incremented.
I have a project where the version was incorrectly bumped.

As you can see from the commit history echoed by the script, there were already releases done (10.0.3) and (10.0.4) but the suggested bump is to 10.0.2

Has this happened to anyone?

<img width="919" alt="screenshot 2018-03-22 20 33 16" src="https://user-images.githubusercontent.com/17492957/37791194-407b05e8-2e11-11e8-94b5-73eb20d773bd.png">

**Comment by webpro** [comment]
Hi @IamTheHttp. Are you sure the git tags (e.g. 10.0.3) actually exist?

**Comment by IamTheHttp** [comment]
Hey @webpro 

I found the issue, it seems that while doing "git pull" it did not fetch all the tags from the remote.

So while in the git log i saw all the commits and all the commits of the tags (like "release 10.0.4", it did not in fact fetch all the tags themselves.

I think the release-it mechanism checks the tags to decide the next version to be bumped, and no the version in the package.json, which might be as intended.

**Comment by webpro** [comment]
> I think the release-it mechanism checks the tags to decide the next version to be bumped, and no the version in the package.json, which might be as intended.

This is indeed intended behavior of release-it. Perhaps you can do a `git fetch --tags` to fetch the tags?

**Comment by IamTheHttp** [comment]
Once we figured out the problem that indeed solved it.
Is it possible to add a warning that the version in the package.json and the last known tag are not the same? it can be a soft warning to maintain backwards compatibility.

I'd be happy to create the PR if you can just point me where to look :)
