### ISSUE TITLE
git error on commit with git bash

### ISSUE THREAD

**Issue by dsebastien** [webpro/release-it#273]
Hello,

I've configured release-it for my project, but I have trouble getting it to do the commits in git bash

I get the following error when executing release-it:
```
? Commit (chore(release): release 0.0.2)? Yes
  release-it:shell { command: 'git commit --message="chore(release): release 0.0.2" ',
  release-it:shell   options: '.',
  release-it:shell   code: 128,
  release-it:shell   stdout: '',
  release-it:shell   stderr: '\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email "you@example.com"\n  git config --global user.name "Your Name"\n\nto set your account\'s default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: unable to auto-detect email address (got \'foo@far.(none)\')\n' } +4s
  release-it:git Error:
  release-it:git *** Please tell me who you are.
  release-it:git
  release-it:git Run
  release-it:git
  release-it:git   git config --global user.email "you@example.com"
  release-it:git   git config --global user.name "Your Name"
  release-it:git
  release-it:git to set your account's default identity.
  release-it:git Omit --global to set the identity only in this repository.
  release-it:git
  release-it:git fatal: unable to auto-detect email address (got 'foo@bar.(none)')
  release-it:git
  release-it:git     at cb (C:/dev/wks/stark/node_modules/release-it/lib/shell.js:37:16)
  release-it:git     at C:\dev\wks\stark\node_modules\shelljs\src\exec.js:121:9
  release-it:git     at ChildProcess.exithandler (child_process.js:278:5)
  release-it:git     at emitTwo (events.js:125:13)
  release-it:git     at ChildProcess.emit (events.js:213:7)
  release-it:git     at maybeClose (internal/child_process.js:927:16)
  release-it:git     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5) +0ms
```

Although I use git everyday in that shell. After searching a bit, I realized that the git commands are executed in an environment that takes into account my Windows environment and not my git bash environment. When I run in git bash, I do have all the config, but it wasn't the case in my Windows environment. 

I think it's probably related to the way you execute the git commands: https://github.com/webpro/release-it/blob/master/lib/git.js#L2

Do you think you could work around that issue to execute the git commands in my current environment?

**Comment by webpro** [comment]
Hi @dsebastien, if Shell.js has a way to execute the commands in an alternative shell, this could be added as a configuration option. There might be a way: https://github.com/shelljs/shelljs#execcommand--options--callback (`{shell: 'path/to/bash'}`). You could give this a shot, test it with Git Bash, and I'm happy to consider your PR.
