### ISSUE TITLE
Roadmap for release-it

### ISSUE THREAD

**Issue by IamTheHttp** [webpro/release-it#278]
Hey.
I was wondering what's the best way to contribute to this project.
Is there any planned roadmap? 
Support for maintaining more platforms?
Known issues(to the author) that need to be tackled?

If help is needed I'd be happy to help!

**Comment by webpro** [comment]
Hi @IamTheHttp, to be honest, there's not really any kind of roadmap. This tool basically does what I want from it, and I'm happy to consider feature requests and bug reports from others.

Issues #266 and #273 are good examples of features that I'm happy to consider, but not personally interested in (at least not atm).

Overall, further improvements of the codebase, tests, and documentation to make it more usable, robust, and easier to develop further are welcome!

From the metrics I can share a few numbers from the last week. Of all sessions...

* 84% happens with the latest two versions (7.3.0 and 7.2.1)
* 72% is run on OSX/macOS, 8% is run on Windows 10, rest is Linux
* 58% is in "interactive mode"
* 20% is run on a CI environment

Are there any improvements or known issues you have in mind?
