### ISSUE TITLE
[Question] How to reenable pretty Github releases

### ISSUE THREAD

**Issue by jvanbruegge** [webpro/release-it#283]
You can see quite easily where I have updated release-it. It's a wonderful tool, but how to I get those back? I put an `increment: "convetional"` in a .release-it.json, but that did not work (that part of the readme is not really clear)

![image](https://user-images.githubusercontent.com/1529052/38771678-891d8d66-4027-11e8-8d7b-db662c6c5361.png)

**Comment by webpro** [comment]
Hi @jvanbruegge, thanks!

* You're looking for the `github.release: true` setting (or `--github.release` from the CLI). This was a [breaking change in v3](https://github.com/webpro/release-it/blob/master/CHANGELOG.md#v30). Also see [GitHub Release](https://github.com/webpro/release-it#%EF%B8%8F-github-release).
* The `increment: "convetional"` has a typo, and also misses the convention, such as `angular` (e.g. `"increment": "convetional:angular"`).

Hope this helps! If anything was unclear, please send a PR or let me know how I can improve the docs.
