### ISSUE TITLE
Should probably not rely on local Babel

### ISSUE THREAD

**Issue by swernerx** [webpro/release-it#292]
First thanks for the great package! I am using it in a ton of my own OSS projects.

I wonder whether it would be possible to transpile the code before uploading it as an npm package. I am trying to move a few of my packages to Babel v7 and seeing some issues with the resolver in npm/yarn trying to resolve a local v6 and v7 requirement. Generally I thought it's somewhat best practice to publish only es5 compat code to npm. I figure people with different Babel v6 versions could also see issues with the setup. Long story short: When installing release-it globally everything is okay, but inside my package it breaks by "prepare" scripts to do the transpilation of my packages.

**Comment by webpro** [comment]
Hi @swernerx, thanks!

> Generally I thought it's somewhat best practice to publish only es5 compat code to npm.

Do you have some resources? I understand the downside, but this is quite annoying for many projects to set up, and it also hurts performance and adoption of new JS features.

In any case, once Babel v7 is stable/released, I'm happy to migrate.

What I could do, is apply `babel-register` only for Node v6 (release-it can run without transpilation on Node v7 and higher). There would still be a `.babelrc` file in the release-it project root, though.

**Comment by webpro** [comment]
I have released [v7.4.3](https://github.com/webpro/release-it/releases/tag/7.4.3) which no longer uses `require('babel-register')` for Node v7 and higher.

i don't think this solves your issue, but it's what all I can offer right now, so I'm going to close this ticket.
