### ISSUE TITLE
Do all non-git tasks first

### ISSUE THREAD

**Issue by Necroskillz** [webpro/release-it#30]
Hey,

Sometimes I run into an issue that cloning fails because rm didn't remove all files. By that time the source repo is already tagged and commited, and I have to manually delete the tag, the commit and force push to reset it to the original state.

I know I could run the script again with --force, but maybe it would be better if all the task that could fail ran first.

For example in order:
1. bump source repo
2. build source repo
3. clone dist repo to .stage
4. copy dist to .stage
5. bump dist repo
6. commit source, dist repo
7. tag source, dist repo
8. push source, dist repo
9. (publish)

**Comment by webpro** [comment]
Mmm that's annoying indeed. In which case is the `rm -rf` not removing all the files?

One downside of such an order is that the process/documentation becomes less clear, and also the source code would be mixed up in terms of src/dist repo tasks. On the other hand, I do like the idea of having all incoming/local stuff execute first, before pushing anything. You will know upfront the dist repo is fine when pushing the src repo. Probably the idea needs to sink in a little :-)

Another route to go might be to offer a `--dist-repo-only` option (or similar). It would just execute the dist repo tasks only (and you wouldn't need to "reset' the src repo).. This is probably easier to implement and would offer a temporary work-around at least.

**Comment by Necroskillz** [comment]
I've had a few cases where `rm` failed to remove some of the files in `.git` folder. Sometimes they become locked or something.

You have a point that with the interactive mode the order would be maybe a little confusing.

Also what might be an improvement, other than the 'only dist' option would be to run `rm` on `.stage` asap and bail if it fails. Other tasks are less likely to fail in my experience.

**Comment by webpro** [comment]
Great idea, I'll put that `rm` earlier in the task chain. Feel free to PR, though.

**Comment by webpro** [comment]
I've released this as v0.1.5 (i.e. fd3d83b7b882ce2ef7ef11e115d4cd185b082224).

**Comment by Necroskillz** [comment]
Thx. Its actually enough if you cd to the stage dir in another cmd, that will cause the rm to fail also.

**Comment by webpro** [comment]
OK, that's the `rm` part. Misconfigured `buildCommand` or `distRepo` values will also make it fail before committing to src repo now.

**Comment by Necroskillz** [comment]
:+1:
