### ISSUE TITLE
Fatal git errors don't cause release to fail

### ISSUE THREAD

**Issue by chooban** [webpro/release-it#301]
I've been trying to get CircleCI set up with release-it, and I've been running into a few issues, one of which is that fatal git errors don't cause the process to fail. This has led to some further issues where I have an npm package at patch version _n_ and a git repo that is still at _n-1_ for tags and commits.

From my Circle output...

```
#!/bin/bash -eo pipefail
echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
git config push.default matching
git config user.mail "rhendry@googlemail.com"
git config user.name "CircleCI"
./.circleci/publish.sh
Local version is 1.0.13, deployed version is 1.0.13
Versions match. Bumping patch...
(node:130) ExperimentalWarning: The fs.promises API is experimental
$ git rev-parse --git-dir
.git
$ git config --get remote.origin.url
git@github.com:chooban/chult.git
$ git diff-index --name-only HEAD --exit-code
$ git rev-parse --abbrev-ref --symbolic-full-name @{u}
origin/master
$ git describe --tags --abbrev=0
1.0.12
WARNING Latest Git tag (1.0.12) doesn't match package.json#version (1.0.13).
$ git show-ref --tags --quiet --verify -- "refs/tags/1.0.12"
$ git log --pretty=format:"* %s (%h)" 1.0.12...HEAD
* All in one shell (58bb2d7)
* Debug mode (b15883a)
* Release v1.0.12 [ci skip] (760a141)
$ bump package.json 1.0.13
$ git add package.json
$ git add . --update
$ git status --short --untracked-files=no
$ git commit --message="Release 1.0.13 [ci skip]" 

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'circleci@41f633618997.(none)')
WARNING No changes to commit. The latest commit will be tagged.
$ git tag --force --annotate --message="Release 1.0.13" 1.0.13

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'circleci@41f633618997.(none)')
WARNING Could not tag. Does tag "1.0.13" already exist? Use --force to move a tag.
```

You can see that the git tag and package version have come unstuck, but the release process carries on, and takes the git tag as the number to bump from (I can see an argument for this, it might even be documented).

I think the bigger issue is that when it comes to committing the changes my broken git config causes a fatal error which is translated to a warning. Since it's a fatal error, at this point we know that release-it won't be able to complete all of its tasks so I would expect it to exit. 

I'm looking into whether or not there's an easy way to validate the config ahead of time so I can add that as a step to the process. And now to try and figure out why the git config is still broken!

_Edit_

The build wasn't working because I was setting `user.mail` instead of `user.email`.

**Comment by webpro** [comment]
Hi @chooban, thanks for the report!

> I think the bigger issue is that when it comes to committing the changes my broken git config causes a fatal error which is translated to a warning.

That's indeed very naive from release-it. I've just fixed this in [7.4.5](https://github.com/webpro/release-it/releases/tag/7.4.5). It should throw and bail out in situations like you've reported.

Sounds like you've fixed your specific issue, great! Thanks again.
