### ISSUE TITLE
how can I use release-it to publish a release and set it to the latest release?

### ISSUE THREAD

**Issue by Nriver** [webpro/release-it#305]
When I publish a new release with release-it, the newer release is not marked as the latest release.

![image](https://user-images.githubusercontent.com/6752679/40642325-5e5ca472-634f-11e8-907b-ae472dcf1f97.png)
As shown above, 0.0.15 is the release I just published, while 0.0.14 is marked as the latest release. Is there any configuration that I missed?

**Comment by webpro** [comment]
I think this means that no actual Github Release was done, it just shows the latest tag. Did you use the `github.release: true` option (or `--github.release` from the command-line) with release-it?

**Comment by Nriver** [comment]
I did not set the GITHUB_TOKEN in environment variable. This issue can be closed.

**Comment by justinlazaro-ubidy** [comment]
@Nriver can i ask how to set up GITHUB_TOKEN in environment variable
