### ISSUE TITLE
Git: arbitrary remote names

### ISSUE THREAD

**Issue by maiamcc** [webpro/release-it#306]
Is there a way to set an arbitrary remote name or does the git release feature only work if your remote is named `origin`? ([Looks that way from the code](https://github.com/webpro/release-it/blob/f451b9999a753030664e8cffbc97d7b8e3df7d87/lib/git.js#L21)...?)

**Comment by webpro** [comment]
Hi, @maiamcc. It currently only works with `origin` now. Apparently you're the first that needs a different name. Happy to accept a PR that features this!

**Comment by webpro** [comment]
The `src.pushRepo` config now accepts both remote url's and names (just released with [v7.6.0](https://github.com/webpro/release-it/releases/tag/7.6.0)).
