### ISSUE TITLE
Rm dist folder before build

### ISSUE THREAD

**Issue by Necroskillz** [webpro/release-it#31]
Any reason you are not doing it? I think it would make sense.

**Comment by webpro** [comment]
That would indeed make a lot of sense. I'll check it out soon. Feel free to submit PR.

**Comment by webpro** [comment]
Thinking of it, I'm a bit wary to just empty/delete the "dist" folder. Projects might have stuff in there (although maybe they should't), and this could easily be part of the build command itself (or e.g. `npm script`).

So I think it's a major change and I'm not sure it's worth it. Thoughts?

**Comment by Necroskillz** [comment]
Exactly - project might have stuff in there ... which we did, and it was stuff we didn't wan't to release.

Imho the build command should build everything that is needed to be released, so the stuff you get from dist folder is exactly what you want to release, and you shouldn't rely on other stuff just 'being there'.

Sure, you can have clean as part of the build command also, so maybe deleting dist folder could be made optional, although by default I see no reason not to delete it.

**Comment by webpro** [comment]
So I've released v1.0.0 and the `distBase` folder gets wiped :-)

**Comment by Necroskillz** [comment]
You didn't publish to npm btw :P

**Comment by webpro** [comment]
Oh my, thanks :-) Now I did!

**Comment by Manjiri1101** [comment]
my yarn build is not working
its throwing the error:
warning package.json: No license field
$ yarn clean:code
warning package.json: No license field
$ rm -rf dist
'rm' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1
can anyone please help me
I am also affreaid of removing "dist" folder
