### ISSUE TITLE
Automatic mode hangs when credentials are not saved

### ISSUE THREAD

**Issue by PatriceVignola** [webpro/release-it#316]
When releasing via the automatic mode (-n flag), if the credentials are not saved, it doesn't ask for them. Instead, the "git push" spinner spins indefinitely while the credentials prompt is hidden. A workaround I found is using the --verbose flag, but it's not ideal of course. I recently cloned my project on a brand new computer and it took me a long time to understand why the release commands were not working all of a sudden.

**Comment by webpro** [comment]
Hi @PatriceVignola, thanks for your bug report. This one is a bit tricky to tackle. There is no way to detect a prompt in such a shell sub-process.

One possible strategy could be to add a timeout for such a task. After the timeout, the task could be retried. But enabling verbose mode for the retry, and getting a prompt to enter credentials would go against CI/non-interactive mode. So I'm leaning towards a timeout and then throw an error such as "Could not push to upstream. Did you configure access to the remote correctly?", and bail out.

The timeout should be pretty long, say at least 30 seconds, to make sure regular Git pushes are not affected by this.

What do you think?
