### ISSUE TITLE
Github Release Assets upload support

### ISSUE THREAD

**Issue by lejenome** [webpro/release-it#32]
Github AP v3 support uploading release assets. It will be very useful to upload the release file on every release (JS file, extension file, Executable file,...).

The API should be supported by node-github first: https://github.com/mikedeboer/node-github/issues/203
API documentation: https://developer.github.com/v3/repos/releases/#upload-a-release-asset

**Comment by webpro** [comment]
Thanks for pointing me to the APIs ;-)

Do you have an example project that has such release assets? Haven't seen them in the wild yet.

**Comment by lejenome** [comment]
Yes, It stills not wildly used, But it is very useful.
You can upload any format.

I will use this feature to automate uploading new releases to GitHub instead of my site.

examples:
- https://github.com/adobe/brackets/releases
- https://github.com/boot2docker/osx-installer/releases
- https://github.com/173210/DFBreak/releases
- https://github.com/stan-dev/rstan/releases

**Comment by webpro** [comment]
OK that's interesting. However, it's not top priority (myself and probably not many people are using it cq would use it).

I can think of a simple configuration for this e.g. `releaseAssets: ["dist/file-%s.dmg", "dist/file-%s.pkg"]`, and then it would upload it as basename.

**Comment by jfairley** [comment]
I would use this. :+1:

**Comment by davelandry** [comment]
I'd also love this feature 👍🏻

**Comment by gld1982ltd** [comment]
:+1:

**Comment by mikedias** [comment]
Another example for uploading assets (I'm using it): https://github.com/remixz/publish-release

**Comment by MichaelMure** [comment]
Any chance that this happen ?

**Comment by webpro** [comment]
I've added and released a first version of this feature in [v2.8.0](https://github.com/webpro/release-it/releases/tag/2.8.0).

How it works? Add for example a `"src.githubAssets": "dist/release.dmg"` (or `"dist.githubAssets": "*.zip"`) file pattern to your config to indicate the files to be uploaded with the release. This can also be an array (it's the first argument to [node-glob](https://github.com/isaacs/node-glob#readme)).

Feedback welcome!

**Comment by MichaelMure** [comment]
Awesome.

I'll test that when I have an actual release to do.

**Comment by MichaelMure** [comment]
I tried in a test repo with the following config:
```json
{
  "verbose": true,
  "src": {
    "commitMessage": "Release %s-preview",
    "tagName": "v%s-preview",
    "githubAssets": [
      "release/*.rpm",
      "release/*.AppImage",
      "release/*.deb",
      "release/*.exe",
      "release/*.dmg"
    ]
  },
  "dist": {
    "baseDir": false
  },
  "npm": {
    "private": "true"
  },
  "github": {
    "release": true,
    "preRelease": true,
    "tokenRef": "GITHUB_TOKEN"
  }
}
```

I get the following error:

> [execute] node-github releases#uploadAsset (start) MichaelMure/Test
> ERROR glob pattern string required

Did I get it wrong ?

**Comment by webpro** [comment]
@MichaelMure Contrary to what I thought, you can't provide an array as glob patterns. However, you can could give a pattern like `"release/*.(rpm|AppImage|deb|exe|dmg)"` (also see [Glob primer](https://github.com/isaacs/node-glob#glob-primer)).

**Comment by MichaelMure** [comment]
What about this ? https://github.com/isaacs/node-glob/issues/217#issuecomment-280831467

**Comment by webpro** [comment]
That's also interesting, thanks. But at first thought, it might be a bit overkill here. I wonder which cases a single pattern string won't cover?

**Comment by MichaelMure** [comment]
Well, yes, you can do the same with a single pattern, but as a user, the array syntax is much easier. I don't have to go read the doc of node-glob and express what I want in a single regex like pattern. I just write an array of simple pattern as I would for `pkgFiles`, it's obvious.

**Comment by webpro** [comment]
You mind opening a PR for this? I'd be happy to add this.

**Comment by MichaelMure** [comment]
Done here: https://github.com/webpro/release-it/pull/102
