### ISSUE TITLE
Automatic new semver value

### ISSUE THREAD

**Issue by vvo** [webpro/release-it#320]
(1. I love release it)

By default release-it asks the user the version for the next release (or consider patch by default), what if it pre-selected that next version in a smarter way by identifying what is the most probable new version based on conventional changelog?

For example we could publish a new major of release-it where by default it would preselect a version or use patch when none found (no compatible conventional changelog).

We could leverage https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump to do so.

Let me know if you are interested in this, thanks!

**Comment by vvo** [comment]
Just saw the recommended bump option: https://github.com/webpro/release-it#recommended-bump

**Comment by webpro** [comment]
:-)
