### ISSUE TITLE
"ERROR Invalid Version" thrown if latest tag is not a semver

### ISSUE THREAD

**Issue by chris-miaskowski** [webpro/release-it#324]
https://github.com/webpro/release-it/blob/a0ecfd40fe72c3ae0ba1bc93f2a28df9e7c11f87/lib/version.js#L34

The line above causes the code to break in runtime if the latest tag doesn't follow a semver format. While this is not a problem most of the time, it does break in some workflows (e.g. nightly builds we tag do not follow a semver format but we don't take them into account when releasing). I think a more defensive check would do the trick here and allow more flexible setups. E.g. a try/catch block around the `semver.neq`.

What do you think?

**Comment by webpro** [comment]
Hi @chris-miaskowski. Thanks for the bug report. Totally agree this should be handled more defensively. I've just released [v7.4.8](https://github.com/webpro/release-it/releases/tag/7.4.8) that includes [this fix](68cf7cbe37c302ac3ed954ab54f1f351a3ec2b37).
