### ISSUE TITLE
Dist Directory When Not Building Artifacts

### ISSUE THREAD

**Issue by destroyerofbuilds** [webpro/release-it#33]
I had a question, and potential workflow issue, when using the latest release of release-it programmatically (as compared to v0.0.15).

I tend to setup an npm run-script called `build` that will lint my node module using `jscs` and `jshint`. I also setup a an npm run-script called `test` to run my Jasmine/Mocha tests. Lastly, I set the `buildCommand` option to be `npm run build && npm run test`.

The idea is that linting and unit testing will be executed before the project is tagged and published.

However, it seems the recent version of `release-it` will, when `buildCommand` is set, create a `dist/` directory. That causes my working directory to include a `dist/` directory.

Now, in my case, because the `dist/` directory is empty, `git` will not attempt to add the directory to my index. Furthermore, `git` will not show the directory when running `git status`.

**Comment by webpro** [comment]
Yes, the `dist` folder is created automatically, which isn't nice if you're not building anything.

If I understand correctly, this is not directly an issue for you now. So either you add the `dist.baseDir` to your `.gitignore`, or this tool should somehow have an option or way to not create this directory. A potential "fix" is to allow `dist.baseDir` to be `null`, and I can install some checks to handle this case.

Any thoughts?

**Comment by destroyerofbuilds** [comment]
@webpro, yes, you're correct. It's not an issue at this time.

For a little more insight, I actually maintain a package that bundles `release-it` with `conventional-changelog` to provide a complete release workflow for other package developers. Therefore, I wouldn't want to impose on each project by requiring that they add `dist/` to their `.gitignore` file. This is also why I wanted to avoid the extra `dist/` directory being created in each project, since it's unexpected for those same developers.

The idea of setting `dist.baseDir` to `null` seems interesting.

Another idea, and I'm just throwing this out there, is to set `baseDir` to `null` by default, unless the project has setup a `dist` repo, or has manually set `baseDir`?

I'm also of the opinion, contrary to #31, that each project should manage their own `dist/` directory as part of their build. If the project's build wasn't creating a `dist/` directory that met the developer's expectations originally, then it shouldn't be up to `release-it` to compensate.

**Comment by webpro** [comment]
@destroyerofbuilds Thanks for the feedback. The `.gitignore` idea was a temporary fix, I'm going to allow `dist.baseDir` to be `null`. Regarding managing that `dist` folder, the idea is that in most cases it's convenient, but you disable it (as of the next release).
