### ISSUE TITLE
Detect if a release is required. If not, exit.

### ISSUE THREAD

**Issue by BBlackwo** [webpro/release-it#330]
Would be nice if we could run this always in our CI and it wouldn't release if there's not a change that requires a release.

So if we just have a `chore` or `docs` commit it should not update the version or publish. It should only bump it on `feat` or `fix`.

My config:

```json
{
  "increment": "conventional:angular"
}
```

I've dug into [the code](https://github.com/webpro/release-it/blob/7.4.8/lib/version.js#L16) are we're relying on [conventional-recommended-bump](https://www.npmjs.com/package/conventional-recommended-bump) so I can raise an issue with them if that's better.

**Comment by BBlackwo** [comment]
I've used a similar tool in the past and it does this check upfront: https://github.com/leonardoanalista/corp-semantic-release#actions-performed

> Detect if a release is required. If not, exit(0);

**Comment by webpro** [comment]
Hi, @BBlackwo! It's not very elegant, but for now maybe you could use the `src.beforeStartCommand` to verify this:

```
"src": {
  "beforeStartCommand": "if [ not release required? ]; then echo 'No changes.'; exit 1; fi"
}
```
