### ISSUE TITLE
Support npm's two factor auth

### ISSUE THREAD

**Issue by Jpunt** [webpro/release-it#335]
Instead of asking for my OTP, `release-it` fails as soon as I want to publish to NPM. I now have to manually run `npm publish`, where I'm properly asked for my OTP. It would be nice if this is integrated!

**Comment by webpro** [comment]
Hi, @Jpunt! That feature should indeed be available.

I've just released [7.5.0-beta.0](https://github.com/webpro/release-it/releases/tag/7.5.0-beta.0) that has this integrated. When provided nothing, the OTP will be prompted for. The OTP can also be provided with `--npm.otp=123456` from the command line (useful for non-interactive/CI mode).

Could you & others please try this before I release this:

```
npm install release-it@beta
```

Thanks!

**Comment by webpro** [comment]
Thanks for trying!

> Just wondering.. how would this work with --npm.otp? I'm guessing such an OTP is only valid for a short period of time, right? Would that be enough for a CI to arrive at this point of the release-script?

The `--npm.otp` argument is indeed an error-prone approach. Not sure how that value could even be obtained without another device (it would defeat the concept of 2FA). Still, there might be use-cases cq. one could prefer to use `-n --npm.otp=123456` to prevent any prompts.

This release is to get things going, I still need to make sure the OTP prompt doesn't show up in CI/`-n` mode.

**Comment by Jpunt** [comment]
Sounds great! 👍

**Comment by webpro** [comment]
Released in [v7.5.0](https://github.com/webpro/release-it/releases/tag/7.5.0)

**Comment by mads-thines** [comment]
Hey!
I'm running 7.6.0, but gets the same error as Jpunt.
When i try to publish through release-it i get the following error:
```
yarn release
yarn run v1.7.0
$ release-it
? Ready to release 1.1.16? Yes
? Show staged files? Yes
M  package.json
? Commit (Release 1.1.16)? Yes
? Tag (1.1.16)? Yes
? Push? Yes
? Publish @adaptagency/fe_tools to npm? Yes
ERROR npm notice
npm notice 📦  @adaptagency/fe_tools@1.1.16
npm notice === Tarball Contents ===
npm notice 858B    package.json
npm notice 298B    main.js
npm notice 288B    main.scss
npm notice 6.2kB   README.md
npm notice 139.7kB yarn.lock
npm notice 539B    src/js/onKeyPress.js
npm notice 593B    src/js/resolvePath.js
npm notice 235B    src/scss/functions/str-remove-whitespace.scss
npm notice 267B    src/scss/functions/str-replace.scss
npm notice 691B    src/scss/functions/str-split.scss
npm notice 175B    src/scss/functions/sum.scss
npm notice 151B    src/scss/mixins/_accessibility.scss
npm notice 467B    src/scss/mixins/_multiplier.scss
npm notice 457B    src/scss/mixins/_rootModifier.scss
npm notice 352B    src/scss/mixins/layout/_full-width.scss
npm notice 1.1kB   src/scss/mixins/layout/_inner.scss
npm notice 957B    src/scss/mixins/layout/_innerBreakpoint.scss
npm notice 1.1kB   src/scss/mixins/layout/README.md
npm notice 552B    src/scss/mixins/typography/_respTypo.scss
npm notice 408B    src/scss/mixins/typography/_respTypoBp.scss
npm notice 1.8kB   src/scss/mixins/typography/README.md
npm notice === Tarball Details ===
npm notice name:          @adaptagency/fe_tools
npm notice version:       1.1.16
npm notice package size:  43.8 kB
npm notice unpacked size: 157.2 kB
npm notice shasum:        62df956dc635c13f09612751f4cd63a21e1b1219
npm notice integrity:     sha512-HKJV8JIcqdE7H[...]kIwss5Nrrjq2A==
npm notice total files:   21
npm notice
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/...-debug.log
```

Any idea what I'm doing wrong? :)
I've tried to both add the -n and --npm.otp argument, but same issue :)

**Comment by webpro** [comment]
Hi, @mads-thines. Not sure if the error is the same:

```
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

Is the npm user configured? You can check with `npm whoami`.

**Comment by mads-thines** [comment]
Hey!
Thanks for getting back so fast :)
Yes, and it returns my user. It also works when using the regular npm publish way. :)

**Comment by webpro** [comment]
And now I remember #95. [This comment](https://github.com/webpro/release-it/issues/95#issuecomment-344176825) might contain a solution.

**Comment by mads-thines** [comment]
Yes, that solved the issue. Thanks!!
If I don't add any arguments it prompts me and it works, but it would be awesome if i could get the `-n` argument to also prompt for otp.
Currently my script is `release: release-it -n`, and then run yarn release --npm.otp=myKey.

Nonetheless, thanks for the help :)

**Comment by webpro** [comment]
> it would be awesome if i could get the -n argument to also prompt for otp.

I see, but `-n` is `--non-interactive` and that would kind of go against a prompt for OTP.

**Comment by mads-thines** [comment]
@webpro and that totally make sense! :)
