### ISSUE TITLE
Add support for OTP

### ISSUE THREAD

**Issue by antonmedv** [webpro/release-it#338]
I have 2FA for all my npm packages. Will be cool to see OTP in release-it.
```
Google Authenticator, for more information see:
https://docs.npmjs.com/getting-started/using-two-factor-authentication
Enter OTP: ***
```

**Comment by webpro** [comment]
It was just added in [v7.5.0](https://github.com/webpro/release-it/releases/tag/7.5.0). Guess I stil need to update the docs!
