### ISSUE TITLE
Optional check for clean working directory?

### ISSUE THREAD

**Issue by shimikano** [webpro/release-it#34]
We've been using your tool as a replacement for [`npm version`](https://docs.npmjs.com/cli/version) for some time now, enjoying the additional features such as dry runs and interactivity.

One thing we're missing though is the check to make sure the git working directory is clean before releasing.

Do you think such an opt-in-able check is within the scope of release-it?

Thank you!

**Comment by webpro** [comment]
Yes. I initially had it that way, but wanted more flexibility. But should
be an option at least indeed. I'll look into it soon.

On Thursday, 17 September 2015, shimikano <notifications@github.com> wrote:

> We've been using your tool as a replacement for npm version
> <https://docs.npmjs.com/cli/version> for some time now, enjoying the
> additional features such as dry runs and interactivity.
>
> One thing we're missing though is the check to make sure the git working
> directory is clean before releasing.
>
> Do you think such an opt-in-able check is within the scope of release-it?
>
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webpro/release-it/issues/34>.
>


-- 
Sent from Gmail Mobile

**Comment by shimikano** [comment]
OK, thanks for the very quick reply!

As a little follow-up, since you mentioned flexibility:

Are you envisioning providing pre/post bump/release hooks in a similar way `npm version` or `grunt-release` do?

(The specific use case we're facing for a post bump command is a Maven Java project where we'd like to run `mvn versions:set ...` in order to also bump the version in the `pom.xml` -- right now, we're abusing `buildCommand` for this.)

**Comment by webpro** [comment]
I've opened a new ticket for this (#35). However, this tool doesn't support bumping a version in XML files (only in JSON files, and only as a 1st level property).

**Comment by webpro** [comment]
@shimikano, please check out [v2.1.0](https://github.com/webpro/release-it/releases/tag/2.1.0) if you're interested. I've added the `requireCleanWorkingDir` option.

**Comment by shimikano** [comment]
Thanks a lot for your efforts, @webpro :thumbsup:

I tried the latest version -- the new `requireCleanWorkingDir` option doesn't seem to work though.

Looking at the code, is the flag [getting passed to the correct invocation](https://github.com/webpro/release-it/blob/2.2.0/lib/tasks.js#L188) (dist vs source repository)?

**Comment by webpro** [comment]
Wow that was a weird oversight. Thanks for the catch, should be fixed now :-)

**Comment by shimikano** [comment]
Thank you very much!

Confirming that `"requireCleanWorkingDir": true` successfully stops the release now.

However, it should be noted that the versions are still bumped and the `buildCommand` is run before the release is canceled.

In my opinion, ideally, the check for a clean working dir should be at the very beginning and the release should be stopped right away without modifying any files. Otherwise, the bumped version files and the dist directory have to be reverted manually in case of an unclean working dir.

**Comment by shimikano** [comment]
Adding to my previous comment, it seems that `"requireCleanWorkingDir": true` wrongly prevents releases in a clean working dir due to the bumped version files.

Here's the output of a sample session:

```
$ git status
On branch master
nothing to commit, working directory clean

$ release-it --verbose
[execute] git config --get remote.origin.url
xxx/foo.git
Release source repo
[execute] git rev-parse --git-dir
.git
[execute] bump package.json 1.0.1
No build command was provided.
[execute] git add package.json
[execute] git diff-index --name-only HEAD --exit-code
package.json
ERROR Working dir must be clean.
```

**Comment by webpro** [comment]
Thanks for your patience. Things should work as intended now in v2.2.2. Let me know if you encounter any issues :-)

**Comment by shimikano** [comment]
Thank you for the fix!

I can confirm that the logic is working fine now.

One more thing I noticed though:

Untracked files are not taken into account for the "clean working directory" check.

I would argue that they should, since otherwise, they inadvertently might end up in a distribution.

To this end, you could consider using `git status [--porcelain]` instead of `git diff-index` for the check, as `npm version` [does for the same purpose] (https://github.com/npm/npm/blob/v3.3.4/lib/version.js#L154).

**Comment by webpro** [comment]
Thanks for the confirmation.

There's indeed multiple levels of "clean" here. I usually add the relevant paths to `.npmignore` and `.gitignore`. So personally I like the "loose" check here, but maybe we can add a `requirePorcelainWorkingDir` or `requireCleanWorkingDir="porcelain"` or something as well later on.

**Comment by shimikano** [comment]
Yes, that's fine.

Adding finer control to the option à la `requireCleanWorkingDir="porcelain"` looks like a viable way to me.

Anyway thanks again for your work!
