### ISSUE TITLE
Pick a Specific Branch or Commit?

### ISSUE THREAD

**Issue by charlwillia6** [webpro/release-it#340]
I am not sure if I am missing it somewhere, but I am not seeing an option to pick the branch or commit that you want to create the release from.  In the API it is the `target_commitish` option.  Is there not a way to do this with release-it?

**Comment by webpro** [comment]
That option indeed doesn't exist (yet). You up for a PR? :-)

What API do are you referring to, Git itself?

**Comment by franciscocpg** [comment]
I need this option (target a specific branch or commit). I'm going to work in a PR for it.
