### ISSUE TITLE
Unable to create github release via proxy (octokit config)

### ISSUE THREAD

**Issue by zchome** [webpro/release-it#348]
Dear release-it team,

would be nice if release-it can support proxy config for github release. Because of firewall restriction, our release to github enterprise server must be sent through a http proxy.

I have checked some documents that the tool "octokit" (used by release-it) supports proxy config.
[Official tutorial](https://www.npmjs.com/package/@octokit/rest/v/14.0.1)
[Proxy issue](https://github.com/octokit/rest.js/issues/770)

I modified source code in `lib/github-client.js` for testing and proxy config of octokit works fine.
```js
const getGithubClient = ({ host, token }) => {
  if (!githubClients[host]) {
    const client = new GitHubApi({
      version: '3.0.0',
      baseUrl: `https://${host === 'github.com' ? 'api.github.com' : host}${host === 'github.com' ? '' : '/api/v3'}`,
      timeout: github.timeout,
      headers: {
        'user-agent': 'webpro/release-it'
      },
	  proxy: 'http://proxy:8080'
    });
```

Regards,
Cheng

**Comment by webpro** [comment]
Hi @zchome! Sorry for late reply. I've just released [v7.6.1](https://github.com/webpro/release-it/releases/tag/7.6.1), that has the `github.proxy` option. Please let me know if it works for you.
