### ISSUE TITLE
Feature: pre-release / npm tag

### ISSUE THREAD

**Issue by webpro** [webpro/release-it#35]
From https://github.com/webpro/release-it/issues/34#issuecomment-141190112.

**Comment by webpro** [comment]
@shimikano, please check out [v2.1.0](https://github.com/webpro/release-it/releases/tag/2.1.0) if you're interested. I've added release types (`pre*`) and a `prereleaseId` option for pre-releases; and the `npm.tag` option to register to npm with a specific tag.

**Comment by shimikano** [comment]
Thank you for this as well!

While the release types implemented here are very handy too, what I actually meant in my comment in #34 is the possibility to _execute custom commands_ before or after the bump/release steps (sorry for my blurry phrasing).

grund-release provides
```js
beforeBump: [], // optional grunt tasks to run before file versions are bumped
afterBump: [], // optional grunt tasks to run after file versions are bumped
beforeRelease: [], // optional grunt tasks to run after release version is bumped up but before release is packaged
afterRelease: [], // optional grunt tasks to run after release is packaged
```
and npm version offers
```json
"scripts": {
  "preversion": "npm test # executed before the bump",
  "version": "npm run build && git add -A dist # executed after the bump",
  "postversion": "git push && git push --tags && rm -rf build/temp # executed after the commit/tag step"
}
```

for this purpose.

**Comment by webpro** [comment]
Ah I see. I actually like that feature as well. Will look into this later.

**Comment by shimikano** [comment]
Looking forward, thank you!
