### ISSUE TITLE
who coded this?

### ISSUE THREAD

**Issue by lopugit** [webpro/release-it#356]
sheesh

**Comment by lopugit** [comment]
thanks for the free software but man, seems like it was done in a rush

**Comment by lopugit** [comment]
I had to patch my own code too https://github.com/lopudesigns/werelease/commit/f5427d0fd3033a4e4cfd066eb0dbbed5dfe68918

**Comment by webpro** [comment]
Hi, @lopugit. If you've got a question or found a bug, I'm happy to hear about it! Feel free to open an issue where we can discuss things in a normal and friendly manner, as outlined in the [code of conduct](./CODE_OF_CONDUCT.md).

**Comment by StevenBlack** [comment]
Proper link to this repo's [code of conduct](https://github.com/webpro/release-it/blob/master/CODE_OF_CONDUCT.md).
