### ISSUE TITLE
How can i set up  GITHUB_TOKEN?

### ISSUE THREAD

**Issue by juztinlazaro** [webpro/release-it#359]
here's my set up. thanks

```
{
  "src": {
    "tagName": "v%s",
    "commitArgs": "-S"
  },
  "requireUpstream": false,
  "requireCleanWorkingDir": false,
  "github": {
    "release": true,
    "releaseName": "Release v%s"
  },
  "npm": {
    "tag": "latest"
  }
}

```

**Comment by webpro** [comment]
For example, if you're on macOS/Linux:

```
export GITHUB_TOKEN=865fa8e05...
```

**Comment by webpro** [comment]
It's documented here: https://github.com/webpro/release-it#%EF%B8%8F-github-release

Let me know if you still have issues.

**Comment by justinlazaro-ubidy** [comment]
@webpro seems like its workin, but got an error
![image](https://user-images.githubusercontent.com/33537770/45878041-4993b980-bdd2-11e8-886a-43173bcfaa4c.png)

thanks sir

**Comment by webpro** [comment]
If the repository's host is not `github.com`, it assumes a GitHub Enterprise instance and uses the repo host, which is `github-ubidy` in your situation. Then the base url for your GitHub Enterprise API becomes `https://github-ubidy/api/v3`.

Does that make sense? Is `github-ubidy` indeed the host of your repo **and** the Github Enterprise instance?

**Comment by justinlazaro-ubidy** [comment]
@webpro hi sir, its my remote in git, got many config in ssh.
![image](https://user-images.githubusercontent.com/33537770/45879025-9a58e180-bdd5-11e8-81e7-53321bc1f68c.png)

![image](https://user-images.githubusercontent.com/33537770/45879037-a2188600-bdd5-11e8-800d-a52af6b2c45d.png)

**Comment by justinlazaro-ubidy** [comment]
@webpro fixed, in my ssh keys and remote. new error comes, maybe this one is on my end.
last question, this repo. is not mine im only a contributor is this possible to that my GITHUB_TOKEN is applicable on it? thanks

![image](https://user-images.githubusercontent.com/33537770/45879409-fbcd8000-bdd6-11e8-945d-f94b8b414c66.png)
