### ISSUE TITLE
Explicit push repository url

### ISSUE THREAD

**Issue by dantman** [webpro/release-it#36]
In one of the npm modules I maintain I use a read-only https url for my origin, and push my changes to my own fork.

I do this so I go through the same pull-request flow that any other contributor goes through and I don't accidentally push code that hasn't already went through CI testing directly to the main repository.

Rather than having the release tags pushed to my fork, failing when it tries to push to the read-only origin, or making my origin writable and accidentally pushing commits to it.
It would be nice to have a `.release.json` option that would make `release-it` push tags directly to the SSH push url for the main repository.

**Comment by webpro** [comment]
That makes sense. So if I understand correctly, you're asking for something like a `src.repo`option that overrides the remote push url (i.e. the result of `git config --get remote.origin.url`) into e.g. the git url of your fork?

**Comment by dantman** [comment]
Not exactly, that sort of implies that the actual config changing.

It's more like an option that makes `release-it` use `git push <repo-url> ...` instead of `git push origin ...`.

**Comment by webpro** [comment]
OK I think I meant the same but explained it not too well. Should be easy to implement.

**Comment by webpro** [comment]
Released as [v2.2.0](https://github.com/webpro/release-it/releases/tag/2.2.0), please let me know if it works for you.
