### ISSUE TITLE
Add more command hooks

### ISSUE THREAD

**Issue by webpro** [webpro/release-it#37]
Also see #34 and #35.

**Comment by webpro** [comment]
@shimikano, I've added some command hooks. I would appreciate your feedback!

I've actually needed more hooks myself for https://medium.com/@webprolific/using-github-pages-the-easy-way-bb7acc46f45b, so that helped :-)

**Comment by shimikano** [comment]
Excellent!

I can confirm that `beforeStageCommand` covers our use case of wanting to keep the version in our `pom.xml` in sync with the primary json version file.

Moreover, we use `beforeStartCommand` to have our tests run again before a release.

Thank you for your work, release-it proved to be a nicely customizable tool (and replacement for `npm version`) for us.

**Comment by webpro** [comment]
Thanks a lot for your feedback, appreciate it!
