### ISSUE TITLE
Integrate Custom Changelog w/ Commit

### ISSUE THREAD

**Issue by Tornquist** [webpro/release-it#376]
## Summary

I would like the ability to interact with the changelog being generated, and then append that to the bottom of both the tag, and the commit message.

## Goal

1. Start Release
2. Changelog is generated
3. Changelog is written to tmp file
4. tmp file is opened in `$DEFAULT_EDITOR`
5. tmp file is saved/editor is closed
6. Release continues

## Changes

* Add flag to optionally interact with changelog
* Add additional indicator on `tagAnnotation` and `commitMessage` for additional lines

## Example

tmp file created

```
Merge commit 1
Feature commit A
Feature commit B
Feature commit C
Merge commit 2
Feature commit D
Feature commit E
```

tmp file saved

```
Merge 1 human description
Merge 2 human description
```

Commit Created:

```
<commitMessage>
<changelog>
```

Tag Created:

```
<tagAnnotation>
<changelog>
```

## Notes

Much of my professional work is on other git hosting services. Because of this, the release system that `release-it` is based around is insufficient for my needs. I store changelogs and descriptions in the commit tag/message when I'm handling releases. There is no single release view, so the tag actually holding the descriptions is super important.

My tag commits are formatted similarly to your defaults (with the additional of more lines).

Is this type of extension something you see as fitting into the vision of `release-it`? If so, I'm happy to build it/help build it. I don't want to frame it all in if you don't want those features included in the product though.

**Comment by PalatinCoder** [comment]
Hi @Tornquist @webpro , as I would like to have that myself I started working on it in #380 :tada:

**Comment by Tornquist** [comment]
Awesome! I haven't started yet. I have a shell script that does it, but nothing regarding integration here.

**Comment by webpro** [comment]
Thanks guys!
