### ISSUE TITLE
want to pass whatBump function to conventionalRecommendedBump

### ISSUE THREAD

**Issue by pOoOf** [webpro/release-it#378]
I want to commit something for which i dont want to increase the version number and also dont want it to be present in the changelog, conventionalRecommendedBump takes an optional whatBump function but in release-it code, that parameter is hardcoded to preset only. is there any way in this plugin to do this or do i need to fix this on my own and send an PR for this?

I want that, if i commit in this format, `wip(temp): temp commit`, then release it should completely ignore this commit for any use

**Comment by webpro** [comment]
Since the configuration is based on primitives (JSON, CLI arguments), I'm afraid there's no clean way to integrate this. Got any ideas?

**Comment by pOoOf** [comment]
I didn't saw your code in detail, sorry can't suggest much here.
For now, I am writing my own tool for generating changelogs as all the tools I found are too opinionated and aren't that configurable.

Thanks.
