### ISSUE TITLE
Allow disabling analytics

### ISSUE THREAD

**Issue by tsjnsn** [webpro/release-it#385]
What analytics is release-it doing? Regardless, there should be an option to disable that.

release-it:catchall { statusCode: 200,
statusMessage: 'OK',
url: 'http://www.google-analytics.com/collect' }

**Comment by webpro** [comment]
First of all, you can disable this with `--disable-metrics`.

It tracks some anonymous variables:

- Number of invocations, and successful exits.
- Version of release-it, Node.js, and OS
- Percentage of non-interactive, dry, and CI runs.
- Exceptions

I will document this soon.
