### ISSUE TITLE
Always selecting git tag version when WARNING: Latest git tag doesn't match package.json#version

### ISSUE THREAD

**Issue by jacoswarts** [webpro/release-it#388]
Greetings,

I'm finding it very hard to change the version to a specific one, when I've changed the package.json version, I get the error:

```
WARNING Latest Git tag (1.0.52-alpha.15) doesn't match package.json#version (1.0.55).
√ Init (release 1.0.52-alpha.16 for <package>)
```
This happens even if I attempt to run `release-it --preRelease=alpha --no-github-release --no-src.tag -n 1.0.55 --force`

What would the process be to set a specific version?

**Comment by webpro** [comment]
That warning is not an error (as the release-it process continues).

The argument order seems to be the issue here, it should be `release-it <increment> [options]`, i.e. `release-it 1.0.55 --preRelease=alpha ...`.

Does that help?

**Comment by webpro** [comment]
> I'm finding it very hard to change the version to a specific one, when I've changed the package.json version

A few more remarks:

* No need to manually do this, release-it should bump the version in `package.json`.
* The `--no-github-release` should be `--no-github.release`.
* The `--force` argument has been [removed in v8](https://github.com/webpro/release-it/blob/master/CHANGELOG.md#v8).

Closing this issue as I feel it's answered properly.
