### ISSUE TITLE
not working in git-bash

### ISSUE THREAD

**Issue by mlarcher** [webpro/release-it#40]
Here is the output I get when calling `release-it` in a git-bash shell on windows:
```
$ release-it
Release source repo
ERROR Cannot read property 'substring' of undefined
```
With the command prompt, I get a more expected:
```
> release-it
Release source repo
? Show updated files? (y/N)
```

**Comment by webpro** [comment]
That would be hard for me to look into, since I don't have that set up. Any help would be appreciated.

However, the source code of release-it doesn't contain any calls to `substring`. Are you sure you don't have any errors during execution of e.g. a `buildCommand`?

**Comment by mlarcher** [comment]
It seems it's the shell.js/exec failing to execute some windows command you pass it. 
Here is the relevant log:
```
$ release-it --debug
{ _: [],
  debug: true,
  e: true,
  npm:
   { version: '0.1.48',
     name: '@mynamespace/ns-module-notification',
     private: false,
     publish: false,
     publishPath: '.',
     tag: 'latest',
     forcePublishSourceRepo: false },
  'non-interactive': false,
  'dry-run': false,
  verbose: false,
  force: false,
  pkgFiles: [ 'package.json' ],
  increment: 'patch',
  prereleaseId: null,
  commitMessage: 'Release %s',
  tagName: '%s',
  tagAnnotation: 'Release %s',
  buildCommand: false,
  changelogCommand: 'git log --pretty=format:\'* %s (%h)\' [REV_RANGE]',
  requireCleanWorkingDir: false,
  src:
   { pushRepo: null,
     beforeStartCommand: false,
     beforeStageCommand: false,
     afterReleaseCommand: false },
  dist:
   { repo: false,
     stageDir: '.stage',
     baseDir: 'dist',
     files: [ '**/*' ],
     pkgFiles: null,
     beforeStageCommand: false,
     afterReleaseCommand: false },
  github:
   { release: false,
     releaseName: 'Release %s',
     tokenRef: 'GITHUB_TOKEN' },
  name: '@namespace/ns-module-notification' }
Release source repo
____ { [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git diff-index --name-only HEAD --exit-code"
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "git diff-index --name-only HEAD --exit-code"' }
ERROR Cannot read property 'substring' of undefined
[promises] Unhandled rejections: 1
Error: TypeError: Cannot read property 'substring' of undefined
    at C:\Users\larcher\AppData\Roaming\npm\node_modules\release-it\bin\release.js:16:15
from execution context:
    at C:\Users\larcher\AppData\Roaming\npm\node_modules\release-it\lib\enquiry.js:90:25
from execution context:
    at Array.reduce (native)
from execution context:
    at C:\Users\larcher\AppData\Roaming\npm\node_modules\release-it\node_modules\when\sequence.js:32:16
from execution context:
    at sequence (C:\Users\larcher\AppData\Roaming\npm\node_modules\release-it\node_modules\when\sequence.js:31:10)
    at module.exports (C:\Users\larcher\AppData\Roaming\npm\node_modules\release-it\lib\enquiry.js:98:12)
    at C:\Users\larcher\AppData\Roaming\npm\node_modules\release-it\node_modules\when\sequence.js:33:22
from execution context:
    at C:\Users\larcher\AppData\Roaming\npm\node_modules\release-it\lib\shell.js:42:21
    at C:\Users\larcher\AppData\Roaming\npm\node_modules\release-it\node_modules\shelljs\src\exec.js:143:7
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

```

**Comment by webpro** [comment]
Apologies for being unresponsive so far. So `shell.js` is executing the following command:

```
C:\Windows\system32\cmd.exe /s /c "git diff-index --name-only HEAD --exit-code"
```

What happens if you run either that whole command manually, and what happens if you run `git diff-index --name-only HEAD --exit-code`, from the Git repo?

Some relevant links:

* https://github.com/SBoudrias/Inquirer.js/issues/272
* https://github.com/eslint/eslint/issues/4018

**Comment by mlarcher** [comment]
When using the first command, I end up in a windows CLI, as if the params were not taken into account:
```
[00:06] Somatt@Ninja:Ihm (master + u=) $C:\\Windows\\system32\\cmd.exe /s /c "git diff-index --name-only HEAD --exit-code"
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits r▒serv▒s.

D:\UwAmp\www\f6\traceone\Ihm>
```
I have to use `exit` to get back to the git-bash shell.

When  using the second command, I get `package.json` output.

For what it's worth, release-it doesn't have this problem on older version of git-bash (1.9.6 I think)

**Comment by webpro** [comment]
Closing, since I'm pretty sure there's not much we can do in this project. Feel free to discuss, though.

**Comment by mlarcher** [comment]
This looks like an escaping issue that could be fixed on either sides. If you're not willing to investigate any further, I won't insist. I just won't use your library even though it looks promising, as most of my team uses git-bash as their goto shell.

**Comment by webpro** [comment]
I don't think it's an escaping issue, please see https://github.com/SBoudrias/Inquirer.js/issues/272#issuecomment-138375494 for an explanation and links to more related details.

**Comment by mlarcher** [comment]
Thanks for the link. I better understand the core issue now. 
One thing puzzles me, though : if the issue is about gitBash not being a true TTY, how come release-it was not crashing in a previous version of it ? 
Anyhow, thanks for your time and keep up the good work.
