### ISSUE TITLE
I can't use --preRelease=beta and conventional:angular together

### ISSUE THREAD

**Issue by dani8art** [webpro/release-it#412]
When I try to release a beta from my package using `"increment": "conventional:angular"` it always releases a prepatch version. I think this is because when I use `--preRelease=beta`, `"increment": "prerelease"` is always set. So `release-it` skips version conventional calculation.

If i execute: 

```shell
release-it --dry-run --debug --preRelease=beta
```

then: 

```shell
release-it:config { _: [],
  release-it:config   'dry-run': true,
  release-it:config   d: true,
  release-it:config   dryRun: true,
  release-it:config   debug: true,
  release-it:config   e: true,
  release-it:config   preRelease: 'beta',
  release-it:config   increment: 'prerelease',
  release-it:config   preReleaseId: 'beta',
```
if I execute: 

```shell
release-it --dry-run --debug
```

then: 

```
release-it:config { _: [],
  release-it:config   'dry-run': true,
  release-it:config   d: true,
  release-it:config   dryRun: true,
  release-it:config   debug: true,
  release-it:config   e: true,
  release-it:config   increment: 'conventional:angular',
```

release-it version: v8.4.0
release-it config:
```
{
    "increment": "conventional:angular",
    "non-interactive": true,
    "requireUpstream": false,
    "preReleaseId": "canary",
    "requireCleanWorkingDir": false,
    "src": {
        "commitMessage": "ci: %s [ci skip]",
        "tagAnnotation": "%s"
    },
    "npm": {
        "publish": false
    },
    "github": {
        "release": true,
        "releaseName": "%s",
        "tokenRef": "GITHUB_TOKEN",
        "draft": false
    },
    "changelogCommand": "git log --pretty=format:'* %s (%h)' [REV_RANGE]"
}
```

How could I do that?

**Comment by dani8art** [comment]
I would like to suggest: 

if we contact: `"increment": "conventional:angular:prerelease",`

then when we `const [system, preset, prerelease] = split(':')` we will have three var, and we can decide with:

```js
const recommendedType = await getConventionalRecommendedBump(preset);
if (prerelease) {
  const preReleaseMapper = { patch: 'prepatch', minor: 'preminor', major: 'premajor' };
  recommendedType = preReleaseMapper[recommendedType];
}
```

**Comment by webpro** [comment]
Thanks for the bug report, @dani8art. I was working on a slightly new implementation for this, but for now I've made a quickfix in [v8.4.1](https://github.com/webpro/release-it/releases/tag/8.4.1). Please let me know if it works for you!

**Comment by webpro** [comment]
And then a fix in [v8.4.2](https://github.com/webpro/release-it/releases/tag/8.4.2) for pre-release continuations. So first a "beta" pre-release is ready, e.g. from `1.4.1` to `1.4.2-beta.0`:

```
release it --preRelease=beta
```

And then this can be incremented to `1.4.2-beta.1`:

```
release it --preRelease
```

**Comment by dani8art** [comment]
Sorry but this fix doesn't work for me, I still get: 
My git log is:

```
* chore: version updated (31fe63d)
* refactor(main): remove all (4d99b4b)
* feat(devops): recomend minor (3d2bf02)
```
If I execute:
```
release-it --dry-run --debug --preRelease=beta
```
then I receive:

```
0.0.4-beta.0
```

but I should receive:
```
0.1.0-beta.0
```

Could you take a look over the solution I've proposed?
Regards.
Thank you.

**Comment by dani8art** [comment]
In addition, It has introduced a bug because it always create a prerelease if you have configured a `preReleaseId`, even if you don't use `--preRelease` flag.

if I execute:
```
release-it --dry-run --debug
```

It creates `0.1.0-canary.0` when it should create `0.1.0`.

**Comment by dani8art** [comment]
@webpro 
Ok, I'll try to open a PR. 

I've mentioned this bug because with the configuration I had, it was broken. Maybe can break others guys.

Regards.

**Comment by webpro** [comment]
This should be fixed in [v9](https://github.com/webpro/release-it/releases/tag/9.0.0-beta.0).
