### ISSUE TITLE
Untracked files not added to staged files after build step

### ISSUE THREAD

**Issue by nidkil** [webpro/release-it#414]
I have noticed that release-it does not stage untracked files. Ones the files have been manually committed it does stage them as expected. I have seen this when release-it is runs in a project for the first time that files are generated by a build command as part of the release proces. The CHANGELOG.md is also missing after the first run of release-it.

Here is an example of `git status` after release-it has run for the first time after I changed the output formats of the build command.

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        dist/vue-build-helper.es.js
        dist/vue-build-helper.js
        dist/vue-build-helper.min.js
        dist/vue-build-helper.min.js.map

nothing added to commit but untracked files present (use "git add" to track)
```

Here is the output of the `Show staged files?` prompt:

```
√  Built in 8.51s.
┌──────────────────────────────────────────────────┐
│file                          size       gzip size│
│dist\vue-build-helper.cjs.js  12.41 KB   3.8 KB   │
│dist\vue-build-helper.es.js   12.17 KB   3.73 KB  │
│dist\vue-build-helper.js      192.31 KB  55.7 KB  │
│dist\vue-build-helper.min.js  144.82 KB  44.97 KB │
└──────────────────────────────────────────────────┘
? Show staged files? Yes
M  CHANGELOG.md
M  dist/vue-build-helper.cjs.js
M  package.json
? Commit (chore: release 0.1.1)? Yes
? Tag (v0.1.1)? Yes
? Push? Yes
? Create a release on GitHub (🚀 Release 0.1.1)? Yes
? Publish vue-build-helper to npm? Yes
```

You can checkout releases 0.1.1 and 0.1.2 [here](https://github.com/nidkil/vue-build-helper) to see the above example.

How to recreate:
- New project.
- Run release-it for the first time.
- When prompted `Show staged files?` select `Yes` and you will only see a subset of the files that were generated.
- After completion run `git status`  and you should see one or more untracked files generated by release-it.

release-it version: 8.3.0

**Comment by webpro** [comment]
Hi, @nidkil!

> I have noticed that release-it does not stage untracked files.

This behavior is intended. So either they should indeed be added manually, or use [`src.addUntrackedFiles: true`](https://github.com/webpro/release-it/blob/8.3.0/README.md#untracked-files). The latter is usually not recommended, as unexpected/unwanted files may get included in the release.

Or are you saying that release-it behaves unexpectedly by staging a (random) subset of files?

**Comment by nidkil** [comment]
Hi Lars,

First of all: great project! Really like what you have done. A real time saver!

I understand that files that are untracked/staged when the release it process start should not be touched by release-it. Except if `addUntrackedFiles` is enabled. But these are files that are generated during the release process. Even the intial version of the CHANGELOG.md file is not picked up and committed.

I feel release-it should distinguish between files that exist before the release process starts and files that are generated during the release process. This last category should be committed by release-it, even if they do not yet exist in the repository (untracked). That is actually how release-it behaves ones they have been initially committed to the repository.

Hope you can follow my thinking.

**Comment by webpro** [comment]
> I feel release-it should distinguish between files that exist before the release process starts and files that are generated during the release process.

This is virtually impossible, because release-it doesn't know what the results of the _user's_ commands are (e.g. `npm run build` or generating `CHANGELOG.md`).

**Comment by nidkil** [comment]
Okay, but I do not understand why it does work after the files have been committed manually to the repo after the first time.

Take for example the CHANGELOG.md which is generated by `conventional-changelog`. The first time it is generated it is not part of the release. On subsequent releases it is picked up and committed. How come this happening automagically?

**Comment by webpro** [comment]
Well, that is weird indeed. You can see what release-it itself is doing with the `--verbose` argument. Let me know if you think release-it has a bug or could improve here. Closing this for now, but feel free to discuss.

**Comment by nidkil** [comment]
Hi Lars,

I'm a little lost now. Does release-it expect the build command and conventional-changelog to commit their own changes when they are called in the release-it hooks?

**Comment by webpro** [comment]
It depends. But generally speaking, "yes".

I do understand this might be unexpected for some people using release-it for the first time. However, it is often considered bad practice to include build artifacts in version control (as they can be generated from source).

This is also the reason I don't put the changelog in [https://github.com/webpro/release-it/blob/master/CHANGELOG.md](./CHANGELOG.md) (besides a few remarks re. breaking changes), but in [releases](https://github.com/webpro/release-it/releases).

In your case, you might want to add e.g. `git add CHANGELOG.md` to the command, or use `--src. addUntrackedFiles` for the first time only.

One more thing: publishing build artifacts to npm is of course fine. This can be managed using `.npmignore` and `.gitignore` (and/or publishing from a directory, e.g. `--npm.publishPath dist`).

**Comment by nidkil** [comment]
> I do understand this might be unexpected for some people using release-it for the first time. However, it is often considered bad practice to include build artifacts in version control (as they can be generated from source).

Good point, I initially did have the `dist` directory in .gitignore, but thought it was needed for NPM. So it is not. Cool I can change that. One problem less :-)

> This is also the reason I don't put the changelog in CHANGELOG.md (besides a few remarks re. breaking changes), but in releases.

I don't understand what you mean. If I look at the GitHub repo the CHANGELOG.md is in the project root like mine.

> In your case, you might want to add e.g. git add CHANGELOG.md to the command, or use --src. addUntrackedFiles for the first time only.

I could do this the first time I call release-it. I still do not understand why this is only needed on the first call. Why isn't it possible to determine which files are untracked & unstaged when release-it starts. Then using this informatin release-it could check after the postbuild hook if there are any files that were not their on startup and stage and commit them. Is their a reason for not doing it this way?

> One more thing: publishing build artifacts to npm is of course fine. This can be managed using .npmignore and .gitignore (and/or publishing from a directory, e.g. --npm.publishPath dist).

Doesn't release-it look at the `files` property in the `package.json` file to determine what to publish to NPM?

**Comment by webpro** [comment]
> If I look at the GitHub repo the CHANGELOG.md is in the project root like mine.

I do have a CHANGELOG.md, but it is not generated. I store the changelog in the "Releases" page of my GitHub projects. See https://github.com/webpro/release-it#github-releases

> I still do not understand why this is only needed on the first call.

Once you `git add`-ed a file, you don't need to do it again, since release-it does this for you:

```
git add package.json
git add . --update      # This (default), or:
git add . --all         # with `src.addUntrackedFiles: true`
```

You can see this with the `--verbose` argument.

> release-it, after the post build hook, could check if there are any files that were not their on startup and stage and commit them. No risk of adding anything that is not generated during the release process and predictable for the user. Is their a reason for not doing it this way?

Lots of files could be generated during any script, and everything within reach would get included in the release. This can lead to unexpected results. I think it's better to opt-in/whitelist, than to opt-out/blacklist.

> Doesn't release-it look at the files property in the package.json file to determine what to publish to NPM?

No, release-it delegates this to `npm publish`. No tricks here, it's like you would `npm publish` from the command line yourself. Again, you can see happening with the `--verbose` argument.

**Comment by nidkil** [comment]
> No, release-it delegates this to npm publish. No tricks here, it's like you would npm publish from the command line yourself. Again, you can see happening with the --verbose argument.

NPM does look at this property, right?

The rest is clear. Thx for your time!

**Comment by webpro** [comment]
> NPM does look at this property, right?

It does: https://docs.npmjs.com/misc/developers

> The rest is clear. Thx for your time!

You're welcome! Thanks for your feedback.
