### ISSUE TITLE
Feature: add links to GitHub and NPM

### ISSUE THREAD

**Issue by nidkil** [webpro/release-it#417]
Git adds the link to the GitHUb repo when a push has completed.

```
$ git push -u origin master
Enumerating objects: 112, done.
Counting objects: 100% (112/112), done.
Delta compression using up to 4 threads.
Compressing objects: 100% (95/95), done.
Writing objects: 100% (112/112), 555.16 KiB | 4.37 MiB/s, done.
Total 112 (delta 23), reused 0 (delta 0)
remote: Resolving deltas: 100% (23/23), done.
To https://github.com/nidkil/vue-test-plugin.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
```

In Webstorm and some consoles this link is clickable, which makes it very easy to go to the repo and do a quick check. It would be cool if release-it could add links to GitHub and NPM when the release process completes succsfully. Can I put in a pull request?

**Comment by webpro** [comment]
I was thinking about exactly the same thing, so your PR is very welcome! Thanks in advance.

**Comment by nidkil** [comment]
Okay I will have a look at it.

**Comment by nidkil** [comment]
I have submitted 3 pull requests for this issue.

**Comment by webpro** [comment]
In [v9.2.0](https://github.com/webpro/release-it/releases/tag/9.2.0).
