### ISSUE TITLE
[question] run from travis-ci

### ISSUE THREAD

**Issue by arthureggert** [webpro/release-it#418]
Hello,

I found release-it today and find it amazing.
But I'm having some trouble to make my release script run from the Travis.
The script run, but it fails when committing back to GH.
I'm pretty sure that is some Travis config, I also looked for solutions over the internet but the most common solution for Travis is calling a deploy.sh script with some configurations and I don't want to do that.

If anyone can provide me with some help with this, I appreciate. 

my repo is: https://github.com/arthureggert/ui

**Comment by webpro** [comment]
Hi @arthureggert, thanks!

Is the issue that the repo is in a "detached HEAD" state on Travis?

Related:

* https://github.com/webpro/release-it/issues/253#issuecomment-369770939
* https://github.com/webpro/release-it/issues/357

**Comment by webpro** [comment]
Does Travis clone using an `https://` Git url? Then Git asks for username and password, but there are no prompts in CI/non-interactive mode (`release-it` detects it's on a CI environment and actives this mode automatically).

With e.g. `git@github.com:arthureggert/ui.git`, SSH is used with Git and you can provide Travis with a public key in order to push to the remote.

**Comment by arthureggert** [comment]
it is working. Thanks @webpro I'm closing this.

**Comment by js2me** [comment]
> Does Travis clone using an `https://` Git url? Then Git asks for username and password, but there are no prompts in CI/non-interactive mode (`release-it` detects it's on a CI environment and actives this mode automatically).
> 
> With e.g. `git@github.com:arthureggert/ui.git`, SSH is used with Git and you can provide Travis with a public key in order to push to the remote.

If I'm using `https://[username]:[token]@github.com:[company]/[project].git` then git is not asking my username and password but I got another problem:

![image](https://user-images.githubusercontent.com/16340911/50371925-352faa80-05d5-11e9-8125-c3c10d079b9e.png)

my `.release-it.json` config
```
{
    "non-interactive": true,
    "git": {
        "requireCleanWorkingDir": false,
        "requireUpstream": false,
        "commit": true,
        "tag": true,
        "push": true,
        "commitMessage": "Release ${name} ${version} [ci skip]"
    },
    "npm": {
        "publish": false
    },
    "github": {
        "release": true
    }
}
```

**Comment by js2me** [comment]
I solved it with putting it before `release-it` command in `.travis.yml`
```
git remote rm origin
git remote add origin https://js2me:${GITHUB_TOKEN}@github.com/acacode/kinka.git
git symbolic-ref HEAD refs/heads/develop
```

**Comment by webpro** [comment]
Thanks for posting this, @js2me! That's helpful for others, too.

@arthureggert Could you please share your solution?

**Comment by GoshaFighten** [comment]
Faced the same issue. @js2me solution works for me. Thanks!

**Comment by webpro** [comment]
Finally got to document things a little in https://github.com/release-it/release-it/blob/master/docs/ci.md
