### ISSUE TITLE
"some anonymous statistical data"?

### ISSUE THREAD

**Issue by limonte** [webpro/release-it#425]
https://github.com/webpro/release-it#metrics

![image](https://user-images.githubusercontent.com/6059356/50241607-92a6da00-03d0-11e9-9ca4-db4ccd3afdec.png)

It would be nice if you could write down in README **what exactly** are you collecting and for **which purposes**?

Also, don't you think it would be polite not to ~spy~ collect anonymous statistical data by default?

**Comment by webpro** [comment]
Hi @limonte!

The exact payload that is going over the wire is here (`cast()` means it's converted to a boolean): https://github.com/webpro/release-it/blob/3772c876a53375a31540d75e9480d68c0dce9885/lib/metrics.js#L24-L45

I'm mostly interested in things like:

* version usage/adoption rate of release-it itself
* whether features such as `github.release` are actually used
* what percentage of runs finish
* exceptions that are thrown

Since it is anonymous, how is this spying? Am I violating any rules?

**Comment by limonte** [comment]
Now I see that you have good intentions but in order to understand that I needed to read `metrics.js` through.

By default, some people like me will react negatively on any king of collecting undefined "anonymous statistical data". Many people are tired of corporations spying on them in order to make more money.

I guess the right thing would be to clarify what data is collected and why. Transparency is the key.

**Comment by webpro** [comment]
> Many people are tired of corporations spying on them in order to make more money.

It's just me, and I have not ever earned a dollar with open source (and never will). But thanks for your two cents ;-)

I'll update the docs soon, and leave this ticket open until it happened.

You can opt-out using `"disable-metrics": true` (top-level).

**Comment by limonte** [comment]
> It's just me, and I have not ever earned a dollar with open source (and never will). But thanks for your two cents ;-)

I would like to change that :) Please add the info to the README about how to make a donation.

Also, consider creating a page (e.g. GitHub pages) with docs and then integrate either https://codefund.app/ or https://www.carbonads.net/ - that will bring some small but stable income.

Have a pleasant evening and thank you for your work!

**Comment by webpro** [comment]
I really appreciate your suggestion, @limonte! Thanks!

**Comment by limonte** [comment]
I don't think this issue should be closed by https://github.com/webpro/release-it/commit/180f131f3a89842a1017d511306b4521142c369b - this commit is not improving things much.

Whats and whys should be listed in **humans** language. Please take a look at the good example of how it should be done: https://www.npmjs.com/policies/privacy#data
