### ISSUE TITLE
Consider auditing npm dependenices as part of release

### ISSUE THREAD

**Issue by humphd** [webpro/release-it#427]
This may not fit with what you want to do, but I thought I'd file it for your consideration.  One thing I was wondering about, is having release-it automatically check whether `npm audit` or https://github.com/IBM/audit-ci or similar passes cleanly.  This could be done with a custom script, similar to running your tests before releasing, so maybe that's where it belongs.  But it seems like the sort of thing one should consider when doing a release, and baking it into release-it would force the issue a bit more.

Thanks for considering this.  I've been playing with release-it, and really love what you've done here.  Amazing idea and execution.

**Comment by webpro** [comment]
Thanks, @humphd!

This could definitely be promoted or motivated by release-it, but I'm hesitant to make it the default. There are probably many things like this that could be "forced" as well (test, lint, you name it). It's just an `npm audit` in `"scripts.beforeStart"` away, I guess.

**Comment by humphd** [comment]
I understand what you're saying about not wanting release-it to become a general purpose build and release tool, and users should rely on scripts to do this.  I'll close, and do it manually for our project.  Thanks.
