### ISSUE TITLE
`npm run release --dry-run` isn't dry :)

### ISSUE THREAD

**Issue by jgentes** [webpro/release-it#435]
Not sure if this is supposed to work properly with the npm shortcut, but it looks like it doesn't get passed through. Works fine with `release-it --dry-run` just not with `npm run release --dry-run`.

**Comment by webpro** [comment]
You should use `--` to [pass arguments to the npm script](https://docs.npmjs.com/cli/run-script.html).

**Comment by jgentes** [comment]
ah, got it, thanks!
