### ISSUE TITLE
Generate release description after version bump tag

### ISSUE THREAD

**Issue by TrevorSayre** [webpro/release-it#437]
Currently I can use the `changelog` script to adjust the initial CLI changelog output to preview the incoming changes for helping determine a version bump. 

However, that same changelog is used for the GitHub release description. I would rather be able to run a different script for this as we generate our final changelogs based on the current tag and a semver sort for the previous tag. We treat changelog generation different for prereleases, etc.

Is there a way to generate the GitHub release description after tagging with the version bump?

**Comment by webpro** [comment]
> Is there a way to generate the GitHub release description after tagging with the version bump?

Not really, except if the `conventional:*` increment is used. This has been [the only use-case](https://github.com/webpro/release-it#custom-or-conventional-changelog) so far I've heard of.

However, I'm happy to accommodate a "second changelog script" of sorts. Feel free to suggest ideas how this would be nice to configure, or even submit a PR.

The first thing that comes to mind is something like `github.changelog` (or `scripts.githubChangelog`) option, which would be the output of `scripts.changelog` by default. Happy to hear more suggestions, though!

**Comment by webpro** [comment]
@TrevorSayre [v9.5.1](https://github.com/webpro/release-it/releases/tag/9.5.1) has a new [`github.releaseNotes`](https://github.com/webpro/release-it#release-notes) option. Let me know what you think!

**Comment by TrevorSayre** [comment]
This worked great, thank you @webpro!
