### ISSUE TITLE
[Feature] Support for conventional changelog

### ISSUE THREAD

**Issue by KapuzenSohn** [webpro/release-it#45]
[Conventional changelog](https://github.com/ajoslin/conventional-changelog) is a commit convention from angular. I think it is really nice and also very readable for everyone.

There is a node dependency called [commitizen](https://github.com/commitizen/cz-cli) where you use `git cz` instead of `git commit`, `git cz` works same like `git commit` but you go through a command line tool which supports you with writing a conventional commit.

I think it would be very nice to have support for this :)

Greetz

**Comment by stephanebachelier** [comment]
@KapuzenSohn you can use the `changelogCommand` property in `.release-it.json`.

**Comment by KapuzenSohn** [comment]
Oh yeah, you are right. I forgot that there was a command for that.

**Comment by KapuzenSohn** [comment]
I will close this issue for now

**Comment by jmendiara** [comment]
If I'm not wrong, `release-it` executes `changelogCommand` before bumping version in `package.json`

`conventional-changelog` expects having the [version bumped before the execution of the command](https://github.com/stevemao/conventional-changelog-cli#recommended-workflow), resulting in `conventional-changelog` to not identify the new version correctly. 

Is there any chance to generate the changelog just after bumping?

**Comment by webpro** [comment]
@jmendiara you could put it in e.g. `src. beforeStageCommand`.

**Comment by jmendiara** [comment]
yeah, but is it possible by using the CLI?

**Comment by webpro** [comment]
@jmendiara It should be (I think e.g. `src.beforeStageCommand="my cmd"` should work). You can also put it in a local `.release.json` file.
