### ISSUE TITLE
Release-it on TeamCity

### ISSUE THREAD

**Issue by Draccoz** [webpro/release-it#451]
Hi there! I am trying to configure a build on TeamCity server.
I added a GITHUB_TOKEN env variable in the build params and after building a project the following step is triggered:
```
#!/bin/bash
set -e -x
release-it %release% -n --verbose --no-npm.publish --github.release --github.assets dist/dist.zip
```
Sadly, no matter what I try it ends up with the following error:
```
Error: fatal: could not read Password for 'https://Draccoz@github.com': No such device or address
     at cb (/usr/lib/node_modules/release-it/lib/shell.js:45:18)
     at /usr/lib/node_modules/release-it/node_modules/shelljs/src/exec.js:127:9
     at ChildProcess.exithandler (child_process.js:301:5)
     at ChildProcess.emit (events.js:182:13)
     at maybeClose (internal/child_process.js:962:16)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```
I don't have much of dev ops experience. Is it something about bad configuration? Or could it be TeamCity issue? How to solve it?

**Comment by webpro** [comment]
Perhaps a **https** Git url was used to clone? This requires username and password to authenticate when pushing to remote. With a **ssh** url the `GITHUB_TOKEN` will be used for authentication.

**Comment by Draccoz** [comment]
The problem is, ssh key is removed after clone to prevent security issues (because some builds can have malicious code...). This leaves me with login + password/token way of authenticating. Could there be a way to force feed login data to release-it via env variables etc?

**Comment by webpro** [comment]
Sorry, I was mixing up the ssh public key (push to Git remote) and `GITHUB_TOKEN` (for GitHub API). But you already got that.

> Could there be a way to force feed login data to release-it via env variables etc?

Unfortunately, I don't think so. The recommended way would be to use a public key. I know that with e.g. Travis CI this key can be provided encrypted. Is there no way for you to configure this?

**Comment by Draccoz** [comment]
I am able to add ssh keys to my build, but if I understand correctly they will always be removed once the repo is cloned. I am basing my reasoning on this: https://confluence.jetbrains.com/display/TCD18/SSH+Keys+Management#SSHKeysManagement-SSHKeyUsage
> The key is removed for security reasons: e.g. the tests executed by the build can leave some malicious code that will access the build agent file system and acquire the key. However, tests cannot get the key directly since it is removed by the time they are running. It makes it harder but not impossible to steal the key. Therefore, the agent must also be secure.

I am still pretty noobish with dev ops, so maybe I understand it wrong? Eventually, is that an issue directed to TeamCity rather than here?

**Comment by webpro** [comment]
Yeah, sorry, that's TeamCity issue. That's why I'm going to close this issue here.

I do see some hints on Google, though, e.g. https://stackoverflow.com/questions/33918088/how-to-set-up-ssh-authenticated-git-commands-in-a-teamcity-build-step

**Comment by Draccoz** [comment]
Yea I will ask TC guys on what am I expected to do, thanks.
As to that answer on SO you provided, I've seen that, but this points back to the key being removed after successful checkout, so doesn't really solve anything in my case (been googling a lot before asking here :P).
Anyway, thanks for quick response. I will try my best to make `release-it` work for me as it's awesome :D.

**Comment by webpro** [comment]
Thanks, @Draccoz! Good luck, wish I had the answer.
