### ISSUE TITLE
After update to 10.0 git.commitArgs doesn't work

### ISSUE THREAD

**Issue by ethyde** [webpro/release-it#452]
Hello,

I juste update to 10.0, but `git.commitArgs` seems doesn't work. I try to configure it from `release-it.json` or CLI.

<img width="1182" alt="capture d ecran 2019-01-19 a 15 54 56" src="https://user-images.githubusercontent.com/409987/51428367-31f30300-1c03-11e9-9d67-b1b27dbbd473.png">

Node : 8.14.1
NPM : 6.4.1

**Comment by webpro** [comment]
Thanks for the report, @ethyde, not sure where that went wrong. Added a test to prevent it from happening again! Released in [v10.0.1](https://github.com/webpro/release-it/releases/tag/10.0.1).
