### ISSUE TITLE
[Question][Feature Request] Bitbucket support

### ISSUE THREAD

**Issue by ozum** [webpro/release-it#458]
Hi,

Is there a plan to support Bitbucket in future?

Thanks a lot.

**Comment by webpro** [comment]
Hi @ozum. Yes, but especially there are plans to allow some form of plugins or "scopes" to customize the release process further. Keep an eye on this project!

**Comment by ozum** [comment]
Great!

**Comment by webpro** [comment]
@ozum, I didn't really look into this the other day. Just to be clear:

* For Git repos, as long as you can push to a remote, release-it can do the same.
* No support for Mercurial yet in release-it.
* Does Bitbucket support releases (like GitHub does)? Looks like it doesn't, so there's not much release-it can do here.

Based on this I assume you meant to ask whether release-it will support Mercurial?

**Comment by ozum** [comment]
No, I didn't mean Mercurial. I use Bitbucket as Git repo, and came across `release-it` yesterday. I read readme and see GitHub and GitLab support and interpreted as it does not support Bitbucket.

**Comment by webpro** [comment]
OK, well, if you can `git push` it, release-it can push it :-)
