### ISSUE TITLE
Insight only in CLI

### ISSUE THREAD

**Issue by destroyerofbuilds** [webpro/release-it#46]
Would you consider moving the `insight` setup into the [fromCli](https://github.com/webpro/release-it/blob/master/lib/release.js#L7) function so that `insight` is not started, and user's aren't asked permission, if `release-it` is used programmatically by other modules?

**Comment by webpro** [comment]
I also would consider removing it entirely as I don't really use it. I wanted to get an idea of usage of this tool and I have it. I think I'll just remove it in the next release.

**Comment by destroyerofbuilds** [comment]
That sounds great @webpro. Thank you!
