### ISSUE TITLE
initial release errors

### ISSUE THREAD

**Issue by jfairley** [webpro/release-it#49]
I have a new project where I'm trying to do an initial release. `release-it` fails on 

```
    "changelogCommand": "git log --pretty=format:'* %s (%h)' [REV_RANGE]",
```

which resolves to 

```
git log --pretty=format:'* %s (%h)' 0.0.0...HEAD
```

As far as I can tell, the range it's building is "`package.version` to HEAD", but in this case, what I have in `package.version` doesn't represent a valid tag.

To get this out, I had to add a custom "changelogCommand" for my initial release. 

```
    "changelogCommand": "git log --pretty=format:'* %s (%h)'",
```

For subsequent releases I will be able to reuse the default "changelogCommand".

I don't mind submitting a PR to fix, but my solution wasn't elegant. IE: how would the script _know_ that a tag cannot be found _because_ it's the initial release? Looking for your thoughts @webpro. If nothing else, the documentation can be updated with this gotcha.

**Comment by jfairley** [comment]
One option would be to inspect whether the result of `git tag --list` is empty. If so, no value for `REV_RANGE`.

**Comment by webpro** [comment]
Hi @jfairley, thanks for the report. I think I've [implemented](https://github.com/webpro/release-it/commit/c0f3b9e6a0503919738d079161e1fbab9f58f5cd) a solution for the initial release in [2.4.0](https://github.com/webpro/release-it/releases/tag/2.4.0). Could you please test if this works for you?

**Comment by jfairley** [comment]
@webpro Sorry it took me a month to test. I just created [a little demo project](https://github.com/jfairley/release-it-test), and it worked great. Thanks!
https://github.com/jfairley/release-it-test/releases
