### ISSUE TITLE
npm-shrinkwrap.json is not being updated to match package.json

### ISSUE THREAD

**Issue by doliver3** [webpro/release-it#52]
I like release-it a bit better than the default npm version command since release-it has better support for named prerelease tags like beta, RC, etc.  I like to run npm shrinkwrap to freeze my dependency versions and I check in my npm-shrinkwrap.json into GIT.

However, I notice that release-it doesn't update the npm-shrinkwrap.json file like npm version does by default. This makes the package.json and the npm-shrinkwrap.json file out of sync showing different version numbers.  

Could you make an update of the npm-shrinkwrap.json version number to match the package.json version number during a release when npm-shrinkwrap.json exists?

**Comment by webpro** [comment]
I'm not sure about the `npm-shrinkwrap.json` structure, but did you try to add it to the `pkgFiles` array in the configuration?

**Comment by eugef** [comment]
Adding `npm-shrinkwrap.json` to the `pkgFiles` works

**Comment by webpro** [comment]
Glad it works for you, @eugef.
