### ISSUE TITLE
access tag name in release hooks

### ISSUE THREAD

**Issue by ayhid** [webpro/release-it#53]
First of all , thanks a lot for this package, it's saving my life on daily basis.
that said, I want to know if it's possible to access the tag name in some of the release hooks, `afterReleaseCommand` for example
Thanks in advance

**Comment by webpro** [comment]
Thanks @ayhid. As per your request, I don't think so (at least not in non-hacky way). Please feel free to submit a PR with this, or I'll be happy to pick it up soon-ish.

**Comment by ayhid** [comment]
@webpro thanks for your quick reply, I'll try to look deeper in the package to see how I can do that.
Any lead/clue to help me start this is more than welcome.

**Comment by webpro** [comment]
The latest release [v2.7.0](https://github.com/webpro/release-it/releases/tag/2.7.0) contains this. Please let me know if it works for you. Also see the updated readme.
