### ISSUE TITLE
Add "pre" to releaseTypes

### ISSUE THREAD

**Issue by bermi** [webpro/release-it#58]
Currently release-it doesn't allow bumping a pre release number.

For example:

Starting version `0.1.0`

```
release-it premajor --dry-run --non-interactive --prereleaseId=rc
[dry-run] bump package.json 1.0.0-rc.0
```

We've increased the major as expected to `1.0.0` and added the `prereleaseId` `rc.0`

If we need to launch another release candidate, **currently there is no way for release-it to increase `rc.0` to `rc.1`**.

Running pre(major/minor/patch) will update the respective semver version, not the `prereleaseId` counter.

```
release-it prepatch --dry-run --non-interactive --prereleaseId=rc
[dry-run] bump package.json 1.0.1-rc.0
```

This could be **solved by adding `pre` to the list of `releaseTypes`** supported by release-it.

```
release-it pre --dry-run --non-interactive --prereleaseId=rc
[dry-run] bump package.json 1.0.0-rc.1
```

@webpro Are there any concerns about including `pre` as legal `releaseTypes`?

**Comment by webpro** [comment]
Released in v2.5.0.
