### ISSUE TITLE
NPM publish from a build folder?

### ISSUE THREAD

**Issue by milesj** [webpro/release-it#60]
I would really like to use this project, but I seem to be getting lost. I actually have 2 issues to report, but thought it best to place them here, as they are somewhat related.

1) There seems to be a severe lack of documentation. I can't find any information on what each property in the `.release.json` file does, how it's used, how to fill it out, etc. I had to start reading the source code to figure out how each property is used -- which was time consuming. It would be great if the docs could be a bit more granular.

2) What I'm really hoping to do is build to a staging folder, like `lib/`, and then NPM publish from that folder so that `lib/` is the "root" folder in the NPM package. It _seems_ like this project could do that, but I've been having a hard time figuring it out (because the lack of docs). At first I thought it would be the `dist` settings, but that seems to require an external repo. Then I tried `src`, which then requires settings from `dist`? It's all rather confusing.

All I'm trying to do is run a "release" command (that builds, versions, and pushes/publishes the project), like so:
- Clean the `lib/` folder.
- Run a build command to compile the `src/` folder to `lib/`.
- Run a linter (EXIT if a failure).
- Run tests (EXIT if a failure).
- Copy over `package.json` (required to be in the lib folder to publish), readmes, and `*.md` files to the `lib/` folder.
- Copy over additional arbitrary files to the `lib/` folder. Like `./data/foo/bar.json` -> `lib/data.json`.
- Increment version.
- Publish the `lib/` folder (as the root) to NPM.
- Push the changes to git.

I simply want to publish from the `lib/` folder so that JS imports can omit the `lib/` from the path. For example:

``` js
// If published from project root
import Matcher from 'interweave/lib/Matcher';

// When published from lib/
import Matcher from 'interweave/Matcher';
```

My current release process simply uses NPM/Yarn scripts, but I'm looking for something a bit more robust. https://github.com/milesj/interweave/blob/master/package.json

**Comment by webpro** [comment]
The docs are indeed not very extensive, my apologies. The good is news, I think, what you want is possible already by setting the `npm.publishPath` setting to `"lib"`.

Let me know if that works for you.
