### ISSUE TITLE
Publish dist folder only to npm, not git

### ISSUE THREAD

**Issue by eugef** [webpro/release-it#71]
If i specify the `buildCommand` then tool tries to add dist folder to git by running `git add dist --all` and fails because in my case dist folder is added to `.gitignore`

How can i publish dist folder only to npm, but not git?

**Comment by eugef** [comment]
I found solution - `dist.baseDir` can be set `false`

**Comment by webpro** [comment]
Glad you found a solution. FYI, you can also set `npm.publishPath` to "dist" to publish the contents of that directory to npm.

**Comment by eugef** [comment]
In my case i need to publish on npm the whole project including src and dist, but i want to exclude dist from git
