### ISSUE TITLE
Option to skip pushing to remote

### ISSUE THREAD

**Issue by szdavid92** [webpro/release-it#72]
I would like to have an option to skip pushing the changes generated by the version bumping to the remote.

My reason is that I would like to publish / release snapshots automatically by CI when the given branch (master) is pushed. I cannot have bump commits for these however, as it would litter the branch excessively. I can live with `package.json` not being updated. Changing the version fis still required because the way of how `npm publish` works, but it can be left un- staged/commited.

What I currently have in my head is turning push off with a cmd line option. If I understand correctly we should skip the 

- commit https://github.com/webpro/release-it/blob/master/lib/tasks.js#L164
- push https://github.com/webpro/release-it/blob/master/lib/tasks.js#L188

tasks; and maybe the `stage`, `stageDir`, `beforeStageCommand` tasks as well?

Tagging, and pushing tags should be unaffected I suppose.

Does it make sense?

**Comment by webpro** [comment]
So if I understand correctly: ideally you only want to tag the current commit, and push this tag, right? Or also e.g. run the build command?

**Comment by szdavid92** [comment]
Right, I want to 
- bump the version, 
- publish the new version to npm,
- tag the commit, 
- push this tag

**Comment by szdavid92** [comment]
created a PR #77

**Comment by webpro** [comment]
Thanks @szdavid92, I've seen your PR. Let's discuss things here.

I'd like to understand the use case better before merging it. As I understand it now, using something like a "skipCommit" option leaves the repo in some modified state by only bumping the version.

* Does the commit you need to tag contain changes in your repo before starting release-it? Plus the bump?
* Does it make sense to change the order of the process and use the `src.beforeStageCommand` and set it to `"npm publish"` (and skip release-it's publish command)?

**Comment by webpro** [comment]
I've just [released](https://github.com/webpro/release-it/releases) the first beta of v3, which includes this feature. Feel free to check it out and I'm happy to hear any feedback.
