### ISSUE TITLE
Github push does not use access token

### ISSUE THREAD

**Issue by StephanBijzitter** [webpro/release-it#78]
This is the config file being used:
```
{
  "github": {
    "tokenRef": "GITHUB_ACCESS_TOKEN"
  }
}
```
Now, it seems that the tokenRef is only used when creating a release on github, but not when pushing a commit to github. This means our CI currently cannot push anything (number 5 in https://github.com/webpro/release-it#what-it-does), which is bad.

**Comment by webpro** [comment]
How about pre-configuring it? Eg. like so: http://stackoverflow.com/a/18936804

**Comment by StephanBijzitter** [comment]
That's quite an interesting idea, I'll take a look when I get back from vacation!

**Comment by webpro** [comment]
Cool :-)

**Comment by StephanBijzitter** [comment]
oh, forgot to reply.
yes, it works.
