### ISSUE TITLE
Bump version in non-JSON files

### ISSUE THREAD

**Issue by AlecRust** [webpro/release-it#79]
Would be great if this could update the version number in non-JSON files.

In my case I have a `.styl` file containing a version number in a comment:

```css
/*!!
Theme Name: Example Theme
Author: Mr Example
Version: 1.1.1
*/
```

Unfortunately if I add this file to `pkgFiles` it fails to update:

![screenshot](https://i.imgur.com/eZcBGgr.png)

**Comment by webpro** [comment]
Hi @AlecRust. That file is not a package/manifest file, and it's not JSON, so it won't work. You could use the `src.beforeStageCommand` option, and automate the desired bump from there.

**Comment by AlecRust** [comment]
Thanks for your reply. Any ideas how I would get the before / after version number to use in `src. beforeStageCommand` so I can perform this with something like [replace](https://www.npmjs.com/package/replace)?

I think the ability to find and update versions in non-JSON files would be a fantastic addition to Release It!

**Comment by webpro** [comment]
There are many ways to accomplish this. You can use a Node script, but you could also replace the version string in-file from the command line (eg. `sed`). You can take the new version number from the bumped `package.json`.

Updating strings in "any file" sounds quite error-prone to me. With the regular manifest files we know it's always the `version` property in the root of the JSON structure.

**Comment by AlecRust** [comment]
Thanks. For anyone searching I used [gulp-bump](https://github.com/stevelacy/gulp-bump) with gulp v4 in the end for this ([example](https://github.com/AlecRust/alec-rust/blob/master/gulpfile.js#L119-L146)).
