### ISSUE TITLE
Run npm build before git push

### ISSUE THREAD

**Issue by miqmago** [webpro/release-it#82]
Maybe this is more a question than an issue, but I'm not understanding the flow.

I've created a plugin which needs to be browserified before publishing to npm. But the plugin is also available under bower. So `build/bundle.js` should be commited to github, tagged and released there.

I've made an npm script like this:

```json
{
  "scripts": {
    "build": "npm run clean && npm run browserify",
    "browserify": "browserify index.js -o build/bundle.js -t [ babelify --presets [ es2015 stage-0 ] ]",
    "clean": "rimraf build && mkdir -p build",
    "prepublish": "npm run build"
  }
}
```

When I use `release-it` to create a new version, all seems to be fine, but it leaves `build/bundle.js` without commiting and pushing it to github, so the release tag does not include the latest build.

I suppose because the flow is this one:

- increment version
- git commit and push
- git tag and push
- npm publish . (here is where prepublish is being run)

My only solution is to remember to run `npm run build` before `release-it`.
Is there any option to make `release-it` run `npm run build` automatically before `git push`?

**Comment by webpro** [comment]
Hi @miqmago! If I understand correctly, you might be looking for the `buildCommand` (or `src.beforeStageCommand`) [configuration setting](https://github.com/webpro/release-it#default-settings). You can use this like `--buildCommand="npm run build"` on the command line, or place a `.release.json` file in the root of the project, e.g.:

```
{
  "buildCommand": "npm run build"
}
```

**Comment by miqmago** [comment]
Awesome, thanks and sorry, because this is already said in documentation :)
Maybe would help an example like the provided one in your answer.
