### ISSUE TITLE
Add support for option to not do a git tag when using release-it

### ISSUE THREAD

**Issue by joerideg** [webpro/release-it#85]
We are using npm prereleases currently as a way to share development versions across projects.

In short a developer publishes a prerelease of a module when he is done with a bunch of work and is ready to push to the git repository. Using release-it its really easy to release! However we would like to have the option to not set a tag everytime we create a prerelease without having to go throug the interactive process.

So the request is to have an config option in .release.json or cli option to to skip tagging the (pre)release.

**Comment by webpro** [comment]
Thanks @joerideg. I think a solution that would also work for this use case is the option to override the default answers to the interactive questions. I'll look into this soon.

**Comment by joerideg** [comment]
Awesome, looking forward to it!

**Comment by webpro** [comment]
I've just released [2.6.0](https://github.com/webpro/release-it/releases/tag/2.6.0). Please let me know if it works for you.

**Comment by joerideg** [comment]
I will check it out tomorrow!

**Comment by joerideg** [comment]
It works btw :)

**Comment by StephanBijzitter** [comment]
I believe I configured our CI to add a tag including the commit hash, but it's been a while.
@joerideg What would the downside of a tag be, though? Wondering if I should remove the tags from our commits or not.

**Comment by joerideg** [comment]
@StephanBijzitter well, in our case we use pre-releases. our CI builds with every push to origin and does a pre-release if succesfull. I just want to git tag my actual releases, not my pre-releases. Otherwise I would end up with 100's of git tags that will never be actually usefull.

**Comment by StephanBijzitter** [comment]
Yeah we do the same, but in our case we have not had any issues with tags as we only tag the npm distributions and do not send tags back to our repository. So I was wondering why you would not want them, but you made a pretty clear case :-)
