### ISSUE TITLE
Add ability to specify different tagName for src and dist

### ISSUE THREAD

**Issue by mark-buer** [webpro/release-it#86]
It'd be nice if we could specify a different `tagName` for the `src` and the `dist`.

A use-case for this is having one git repo for both of the `src` and `dist` (i.e. separate orphaned branches), a simultaneous release on two such branches cannot have the same `tagName`.

It's probably make sense to make all three of `commitMessage`, `tagName ` and `tagAnnotation` be separately specifiable for `dist`?

The new configuration properties could exist within the `/dist` JSON configuration tree, and each could default to the base property if not specified. This seems to be a backwards compatible change.

**Comment by webpro** [comment]
That sounds useful and feasible. A PR is welcome, or I'll look into it myself later on.

**Comment by webpro** [comment]
The latest release [v2.7.0](https://github.com/webpro/release-it/releases/tag/2.7.0) contains this. Please let me know if it works for you.

**Comment by mark-buer** [comment]
The changes are very effective 👍 

Thank you!

**Comment by webpro** [comment]
Thanks for your feedback :-)
