### ISSUE TITLE
Add support for generating the changelog based on `src.tagName`

### ISSUE THREAD

**Issue by sampi** [webpro/release-it#92]
If I specify `src.tagName`, the changelog will still be generated based on the version number from the `package.json` so I'll get the whole changelog for every release.

I replaced `[REV_RANGE]` with `$(git describe --tags $(git rev-list --tags --max-count=1))...HEAD` in my script and now it runs correctly, but respecting `src.tagName` would be the best solution.

**Comment by webpro** [comment]
Thanks for reporting this, I'll look into it soon.

**Comment by webpro** [comment]
The changelog is indeed derived from `pkg.version`, assuming you're not providing the `--increment` argument yourself.

The `src.tagName` is a formatting string, and shouldn't be a hard-coded version number.

Why don't you provide the `--increment` argument? E.g. `release-it --increment 0.5.1` or just `release-it patch`.

**Comment by sampi** [comment]
You can see my `.release.json` here: https://github.com/Tradeshift/tradeshift-ui/blob/master/.release.json

I'm prefixing the tag with `v`.

I wanted to go from `8.0.0-beta.2` to `8.0.0`, so I just ran `release-it 8.0.0` (or more precisely `yarn release -- 8.0.0`) and it just took the whole changelog.
Would the right way to do it be `yarn release -- --increment="major"`?

The yarn/npm script is defined here, it just loads the appropriate config file explicitly: https://github.com/Tradeshift/tradeshift-ui/blob/master/package.json#L29

**Comment by webpro** [comment]
Yes, you need the "extra pair of dashes" to pass arguments through to the program (release-it in this case):

```
yarn release -- --increment="major"
yarn release -- major
```

**Comment by sampi** [comment]
I used the extra dashes, but then you're saying that I should always use the increment values, instead of specifying exact version number. I'll keep that in mind.

This is getting a little off topic, but I think there's another reason why I didn't get the right values..
I think something is wrong with my repo, I tried running the commands by themselves:
```
~/Development/tradeshift-ui$ git tag
v6.1.0
v6.1.1
v6.1.2
v7.0.0
v7.0.0-rc.7
v7.0.0-rc.8
v7.0.0-rc.9
v7.0.1-alpha.1
v7.1.0
v7.1.0-spotlight.0
v7.1.0-spotlight.1
v7.2.0
v7.2.0-alpha.1
v7.2.0-alpha.2
v7.2.0-rc.1
v7.2.0-spotlight.2
v7.2.1
v7.2.1-0
v8.0.0
v8.0.0-alpha.1
v8.0.0-beta.1
v8.0.0-beta.2
v8.0.1
v8.0.2

~/Development/tradeshift-ui$ git describe --tags --abbrev=0
v6.1.2

~/Development/tradeshift-ui$ git describe --tags $(git rev-list --tags --max-count=1)
v8.0.2
```

I won't bother you with that, I'll just use the increment values, so the right values are inserted in the hash replacements instead of the package version.

**Comment by webpro** [comment]
I would recommend `yarn release -- minor`. But `yarn release -- 8.0.0` should work just as well (especially if a repo behaves weird regarding tags). Sorry if I wasn't clear on this.
