### ISSUE TITLE
Specifying `github.preRelease='true'` throws an error

### ISSUE THREAD

**Issue by sampi** [webpro/release-it#94]
When specifying `github.preRelease` in the command line, I get an error from the GitHub API saying that it's a string and not a boolean.

**Comment by webpro** [comment]
Did you use/try `--github.preRelease` without a value (e.g. `--github.preRelease='true'`)?

**Comment by sampi** [comment]
I tried to use it through an npm script, and I tried the following:

`"release": "release-it --github.preRelease=true"`

`"release": "release-it --github.preRelease='true'"`

`"release": "release-it --github.preRelease=\"true\""`

and I always got the same error.

The solution I found was to have separate `.release.json` files for prereleases and releases.

**Comment by webpro** [comment]
No, really, without a value:
```
release-it --github.preRelease
```

**Comment by sampi** [comment]
I haven't tried that. What should happen if I do?
Does it get registered as `false` so I should have my config file include it as true or is it the other way?

Ideally, I'd like to have only one config file and two separate npm-scripts, the first to release a normal version, the other to create a prerelease.

**Comment by webpro** [comment]
This setting is `false` by default, and by adding the command-line argument it becomes `true`. By using e.g. `npm run release -- --github.preRelease` I think you can achieve what you want.

**Comment by webpro** [comment]
I think we can close this? :-)

**Comment by sampi** [comment]
yes, thanks for the help!
