### ISSUE TITLE
Optionally reinstall dependencies

### ISSUE THREAD

**Issue by sudo-suhas** [webpro/release-it#96]
Would it be possible to optionally enable reinstallation of node modules similar to [np](https://github.com/sindresorhus/np)? 

Although an edge case, reinstalling modules before running tests can avoid build breaking after pushing to master branch like on this instance - https://travis-ci.org/sudo-suhas/elastic-builder/jobs/228378612.

**Comment by webpro** [comment]
You could make `npm install` part of e.g. `buildCommand` or `src. beforeStartCommand `?

Also see https://github.com/webpro/release-it#command-hooks

Does this help?

**Comment by sudo-suhas** [comment]
I would have to rm - rf before doing that to ensure the latest minor/patch is installed. But I am wondering if it is important enough to include in the core. Also, would prefer not adding another dependency.

**Comment by webpro** [comment]
Closing this, as it's trivial to put `npm install/update` before running this or in one of the command hooks.
