### ISSUE TITLE
Errors are being swallowed

### ISSUE THREAD

**Issue by KaidenR** [webpro/release-it#97]
I have a script that is running release-it as part of a deploy process and need to be able to tell that something went wrong and abort the rest of the script.

The problem is that when an error happens (like if `requireCleanWorkingDir` is true and the working directory is not clean), those errors are not thrown unless the `debug` config is set. I don't want all the other logging that comes with the debug flag so I can't use that.

This is happening here: https://github.com/webpro/release-it/blob/master/lib/release.js#L40

Maybe there could be a new config option for this. It could be something like `catchErrors: false` or `emitErrors: true`.

BTW: Really great job on this repo. It's super helpful!

**Comment by webpro** [comment]
I see your point, I'll look into it soon. PR is welcome, of course :-)

**Comment by webpro** [comment]
In non-debug mode, the error is thrown. The process logs the error message (not the stack trace), and exits with a non-zero exit code (`1`). With `--debug` enabled, the stack trace is also printed.

For example (with `"requireCleanWorkingDir": true`):

```
❯ release-it
Release source repo
ERROR Working dir must be clean.
```

Looks like this behaves as expected, right?

PS I did notice that errors from build commands (e.g. the `buildCommand` config) are being swallowed (unless the `--verbose` option is enabled). This I'll fix.

**Comment by webpro** [comment]
I have made some improvements, as mentioned. Therefore, I'm closing this issue. I'm happy to hear about your feedback, or discuss further.
