### ISSUE TITLE
package-lock version not updated

### ISSUE THREAD

**Issue by sudo-suhas** [webpro/release-it#99]
`package-lock.json` was newly added in npm 5. It is similar to `npm-shrinkwrap.json`. Running `release-it` does not update the version of package in lock file.
Example [`package.json`](https://github.com/sudo-suhas/elastic-builder/blob/master/package.json), [`package-lock.json`](https://github.com/sudo-suhas/elastic-builder/blob/master/package-lock.json)

**Comment by webpro** [comment]
You can add `"package-lock.json"` to the `pkgFiles`.

Feel free to open a PR that adds this by default.

**Comment by sudo-suhas** [comment]
release-it uses [`JSON.stringify`](https://github.com/webpro/release-it/blob/71bef866f19c146af92995293dfc747a6bdec2c8/lib/shell.js#L116) for writing the `package.json` file. However, npm 5 [detects and preserves indentation](http://blog.npmjs.org/post/161081169345/v500) for `package.json`, `package-lock.json`, and `npm-shrinkwrap.json`. Would it be better to delegate to [`npm version`](https://docs.npmjs.com/cli/version)?

**Comment by webpro** [comment]
* Is `npm version` available as a Node package?
* release-it still needs to bump the version in e.g. `bower.json` (or whatever manifest file users might want to bump), so we'd still need `JSON.stringify` here.

**Comment by webpro** [comment]
There are (still) some issues around npm's `package-lock` file. I'm closing this issue for now, as you can include it with a release if you want with e.g. `pkgFiles: ["package.json", "package-lock.json"]`.

**Comment by seanodell** [comment]
Having this same issue. Wondering what "pkgFiles" is.

**Comment by webpro** [comment]
The `pkgFiles` option contains the array of files that the `version` property should be updated in, e.g.:

```
pkgFiles: ["package.json", "package-lock.json"]
```

The upcoming v11 delegates this to `npm version` which updates the relevant files (and the `pkgFiles` option is removed altogether), you can try this with:

```
npm install release-it@beta
```

**Comment by seanodell** [comment]
Geez ... I should have read the entire README first. Totally documented and I missed it. Thanks!
